<script setup>
import { ref, onMounted } from 'vue';
import { useRoute } from 'vue-router';
import { useClinicContextStore } from '../../stores/clinicContext';
import { usePrescriptionStore } from '../../stores/prescriptions';
import { prescriptionService as service } from '../../services/prescriptions';
import PrescriptionStatusBadge from '../../components/prescriptions/PrescriptionStatusBadge.vue';
import PrescriptionActions from '../../components/prescriptions/PrescriptionActions.vue';
import FormErrors from '../../components/ui/FormErrors.vue';
import '../../../css/prescriptions.css';
const route = useRoute(), context = useClinicContextStore(), store = usePrescriptionStore();
const p = ref(null), options = ref(null), history = ref(null), error = ref(null), busy = ref(true);
async function load(message) { busy.value = true; error.value = null; if (message) store.notice = message; try { const [record, config, activity] = await Promise.all([service.get(route.params.id), service.options(), service.activity(route.params.id)]); p.value = record.data.data; options.value = config.data.data; history.value = activity.data.data; } catch(e) { error.value = e; } finally { busy.value = false; } }
async function historyPage(page) { try { history.value = (await service.activity(p.value.id, page)).data.data; } catch(e) { error.value = e; } }
onMounted(() => load());
</script>
<template><p class="patient-breadcrumb"><RouterLink to="/app/prescriptions">← Prescriptions</RouterLink></p><FormErrors :error="error" /><p v-if="busy" role="status">Loading prescription…</p><template v-else-if="p"><div class="patient-page-header"><div><h1>{{ p.prescription_number }}</h1><PrescriptionStatusBadge :status="p.status" :labels="options.statuses" /></div><div class="rx-row-actions"><RouterLink v-if="context.can('prescriptions.print')" class="btn-secondary" :to="`/app/prescriptions/${p.id}/print`">Print</RouterLink><RouterLink v-if="p.editable && context.can('prescriptions.update')" class="btn" :to="`/app/prescriptions/${p.id}/edit`">Edit</RouterLink><PrescriptionActions :prescription="p" @changed="load" /></div></div><p v-if="store.notice" class="rx-notice" role="status">{{ store.notice }}<button aria-label="Dismiss notification" @click="store.notice = ''">×</button></p>
<div class="rx-grid mt-5"><section class="clinic-panel rx-section rx-detail-info"><h2>Patient Information</h2><strong>{{ p.patient.full_name }}</strong><p>{{ p.patient.patient_number }} · {{ p.patient.gender }} · {{ p.patient.age ?? '—' }} years</p><p>{{ p.patient.phone || 'No phone recorded' }}</p><RouterLink v-if="context.allowed('patients')" :to="`/app/patients/${p.patient_id}/overview`">View Patient</RouterLink></section><section class="clinic-panel rx-section rx-detail-info"><h2>Prescriber Information</h2><strong>{{ p.doctor.full_name }}</strong><p>{{ p.doctor.specialty }}</p><p>License: {{ p.doctor.license_number || '—' }}</p><p>{{ p.branch.name }}</p></section></div>
<section class="clinic-panel rx-section rx-detail-info mt-5"><h2>Prescription Information</h2><p>Date: {{ p.prescription_date }}</p><p v-if="p.diagnosis">Clinical indication: {{ p.diagnosis }}</p><p v-if="p.notes">Notes: {{ p.notes }}</p><p v-if="p.internal_notes">Internal notes: {{ p.internal_notes }}</p><p v-if="p.cancellation_reason">Cancellation reason: {{ p.cancellation_reason }}</p><p v-if="p.appointment">Appointment: <RouterLink v-if="context.allowed('appointments')" :to="`/app/appointments/${p.appointment_id}`">{{ p.appointment.appointment_number }}</RouterLink><span v-else>{{ p.appointment.appointment_number }}</span></p></section>
<section class="clinic-panel rx-section mt-5"><h2>Medication Orders</h2><div class="table-scroll"><table class="rx-table"><thead><tr><th>Medication</th><th>Strength</th><th>Dose</th><th>Route</th><th>Frequency</th><th>Duration</th><th>Quantity</th><th>Instructions</th><th>Dispensing Status</th></tr></thead><tbody><tr v-for="item in p.items" :key="item.id"><td>{{ item.medication_name }}</td><td>{{ item.strength || '—' }}</td><td>{{ item.dose }}</td><td>{{ options.routes[item.route] }}</td><td>{{ item.frequency === 'custom' ? item.custom_frequency : options.frequencies[item.frequency] }}</td><td>{{ item.duration }}</td><td>{{ item.quantity || '—' }}</td><td>{{ item.instructions || '—' }}</td><td><PrescriptionStatusBadge :status="item.status" :labels="options.statuses" /><small>{{ item.dispensed_quantity }} dispensed</small></td></tr></tbody></table></div></section>
<section class="clinic-panel rx-section mt-5"><h2>Activity / History</h2><p v-for="event in history?.data" :key="event.id" class="py-2">{{ event.action.replace('prescription.', 'Prescription ').replaceAll('_',' ') }} · {{ event.actor_name }} · {{ event.created_at }}</p><div v-if="history?.last_page > 1" class="rx-form-actions"><button class="btn-secondary" :disabled="history.current_page <= 1" @click="historyPage(history.current_page - 1)">Previous</button><button class="btn-secondary" :disabled="history.current_page >= history.last_page" @click="historyPage(history.current_page + 1)">Next</button></div></section></template></template>
