import { test, expect } from '@playwright/test';

test('admin onboards a clinic, owner accesses it, suspension revokes access', async ({ page }) => {
    const errors=[];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/app/admin');
    await expect(page).toHaveURL(/app\/login/);
    await page.getByLabel('Email', { exact:true }).fill('browser-admin@example.test');
    await page.getByLabel('Password', { exact:true }).fill('BrowserTestPass123');
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await expect(page.getByRole('heading',{name:'SaaS management'})).toBeVisible();
    await page.getByRole('button',{name:'Plans',exact:true}).click();
    await page.getByLabel('Name',{exact:true}).fill('Starter');
    await page.getByRole('button',{name:'Create plan',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('Plan created.');
    await page.getByRole('button',{name:'Clinics',exact:true}).click();
    await page.getByLabel('Clinic name',{exact:true}).fill('Browser Clinic');
    await page.getByLabel('Unique clinic code').fill('browser-clinic');
    await page.getByLabel('Plan',{exact:true}).selectOption({index:1});
    await page.getByLabel('Owner name').fill('Clinic Owner');
    await page.getByLabel('Owner email').fill('browser-owner@example.test');
    await page.getByLabel('Owner password',{exact:true}).fill('OwnerTestPass123');
    await page.getByLabel('Confirm password',{exact:true}).fill('OwnerTestPass123');
    await page.getByRole('button',{name:'Create clinic',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('Clinic created');
    await page.getByRole('button',{name:'Manage',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Manage Browser Clinic'})).toBeVisible();
    await page.getByLabel('Branch name').fill('Over limit');
    await page.getByRole('button',{name:'Add branch'}).click();
    await expect(page.getByRole('alert')).toContainText('branch limit');
    await page.screenshot({ path:'test-results/saas-admin.png', fullPage:true });
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    await page.screenshot({ path:'test-results/saas-admin-mobile.png', fullPage:true });
    await page.setViewportSize({width:1280,height:720});
    await page.getByRole('button',{name:'Sign out'}).click();
    await expect(page).toHaveURL(/app\/login/);
    await page.getByLabel('Email',{exact:true}).fill('browser-owner@example.test');
    await page.getByLabel('Password',{exact:true}).fill('OwnerTestPass123');
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await expect(page.getByText('Main branch',{exact:true})).toBeVisible();
    await page.reload();
    await expect(page.getByText('Main branch',{exact:true})).toBeVisible();
    await page.goto('/app/admin');
    await expect(page).toHaveURL(/app\/clinics/);
    await page.getByRole('button',{name:'Sign out'}).click();
    await expect(page).toHaveURL(/app\/login/);
    await page.getByLabel('Email',{exact:true}).fill('browser-admin@example.test');
    await page.getByLabel('Password',{exact:true}).fill('BrowserTestPass123');
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await page.getByRole('button',{name:'Manage',exact:true}).click();
    await page.getByLabel('Clinic status').selectOption('suspended');
    await page.getByRole('button',{name:'Save settings'}).click();
    await expect(page.getByRole('status')).toContainText('Clinic settings saved.');
    await page.getByRole('button',{name:'Sign out'}).click();
    await expect(page).toHaveURL(/app\/login/);
    await page.getByLabel('Email',{exact:true}).fill('browser-owner@example.test');
    await page.getByLabel('Password',{exact:true}).fill('OwnerTestPass123');
    await page.getByRole('button',{name:'Sign in',exact:true}).click();
    await expect(page.getByText(/no active clinic memberships/)).toBeVisible();
    expect(errors).toEqual([]);
});
