import { test, expect } from '@playwright/test';

test('clinic administration uses dedicated routes and preserves tenant access', async ({ page }) => {
    test.setTimeout(180000);
    const errors=[];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/app/admin/clinics');
    await expect(page).toHaveURL(/app\/login/);
    await page.getByLabel('Email',{exact:true}).fill('browser-admin@example.test');
    await page.getByLabel('Password',{exact:true}).fill('BrowserTestPass123');
    await page.getByRole('button',{name:'Sign in'}).click();
    await expect(page.getByRole('heading',{name:/Welcome back/})).toBeVisible();
    await page.getByRole('link',{name:/Users/}).click();
    await expect(page.getByRole('heading',{name:'System Users'})).toBeVisible();
    await expect(page.locator('tbody').getByText('Browser Admin',{exact:true})).toBeVisible();

    await page.getByRole('link',{name:/Subscription Plans/}).click();
    await expect(page.getByRole('heading',{name:'Create Subscription Plan'})).toHaveCount(0);
    await page.getByRole('link',{name:/Add New Plan/}).click();
    await expect(page).toHaveURL(/admin\/plans\/create$/);
    await page.getByLabel('Plan Name').fill('Starter');
    await page.getByLabel('Plan Code / Slug').fill('starter');
    await page.getByLabel('Patient Management').check();
    for (const feature of ['Appointments', 'Doctors / Clinicians', 'Prescriptions', 'Billing', 'Electronic Medical Records']) {
        await page.getByLabel(feature, { exact: true }).check();
    }
    await page.getByRole('button',{name:'Create Plan'}).click();
    await expect(page).toHaveURL(/admin\/plans\/1\?created=1$/);
    await expect(page.getByRole('status')).toContainText('Subscription plan created successfully.');
    await expect(page.getByRole('button',{name:'Delete Plan'})).toHaveCount(0);
    await page.getByRole('button',{name:/More/}).click();
    await expect(page.getByRole('button',{name:'Delete Plan'})).toBeVisible();
    await page.getByRole('link',{name:'Features',exact:true}).click();
    await expect(page.getByText('Enabled · Patient Management')).toBeVisible();
    await page.goBack();
    await expect(page).toHaveURL(/admin\/plans\/1\?created=1$/);
    await page.reload();
    await expect(page.getByRole('heading',{name:'Starter'})).toBeVisible();

    await page.getByRole('link',{name:/Clinics \/ Tenants/}).click();
    await expect(page).toHaveURL(/admin\/clinics$/);
    await expect(page.getByRole('heading',{name:'Create Clinic'})).toHaveCount(0);
    await page.getByRole('link',{name:/Add New Clinic/}).first().click();
    await expect(page).toHaveURL(/admin\/clinics\/create$/);
    await page.getByLabel('Clinic name').fill('Browser Clinic');
    await page.getByLabel('Unique clinic code').fill('browser-clinic');
    await page.getByLabel('Plan').selectOption('1');
    await page.getByLabel('Owner name').fill('Clinic Owner');
    await page.getByLabel('Owner email').fill('browser-owner@example.test');
    await page.locator('input[type="password"]').first().fill('OwnerTestPass123');
    await page.getByLabel('Confirm password').fill('OwnerTestPass123');
    await page.getByRole('button',{name:'Create Clinic'}).click();

    await expect(page).toHaveURL(/admin\/clinics\/1\?created=1$/);
    await expect(page.getByText('Clinic created successfully.')).toBeVisible();
    await page.reload();
    await expect(page.getByRole('heading',{name:'Browser Clinic'})).toBeVisible();
    await page.getByRole('link',{name:'Branches',exact:true}).click();
    await expect(page).toHaveURL(/admin\/clinics\/1\/branches$/);
    await page.getByRole('button',{name:/Add Branch/}).click();
    await page.getByRole('dialog').getByLabel('Branch name').fill('Over limit');
    await page.getByRole('dialog').getByRole('button',{name:'Add Branch'}).click();
    await expect(page.getByRole('alert')).toContainText('branch limit');
    await page.getByRole('dialog').getByRole('button',{name:'Cancel'}).click();

    await page.getByRole('link',{name:'Members',exact:true}).click();
    await expect(page).toHaveURL(/admin\/clinics\/1\/members$/);
    await page.goBack();
    await expect(page).toHaveURL(/admin\/clinics\/1\/branches$/);
    await page.goForward();
    await expect(page).toHaveURL(/admin\/clinics\/1\/members$/);
    await page.screenshot({path:'test-results/clinic-management.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
    await page.screenshot({path:'test-results/clinic-management-mobile.png',fullPage:true});

    await page.getByRole('button',{name:'Open menu'}).click();
    await page.getByRole('button',{name:'Sign out'}).click();
    await page.getByLabel('Email',{exact:true}).fill('browser-owner@example.test');
    await page.getByLabel('Password',{exact:true}).fill('OwnerTestPass123');
    await page.getByRole('button',{name:'Sign in'}).click();
    await expect(page).toHaveURL(/app\/dashboard$/);
    await page.goto('/app/clinics');
    await expect(page).toHaveURL(/app\/dashboard$/);
    await page.goto('/app/clinics?switch=1');
    await expect(page.getByRole('heading', { name: 'Choose your clinic' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    await page.screenshot({ path: 'test-results/clinic-switcher-mobile.png', fullPage: true });
    await page.getByRole('button', { name: /Browser Clinic/ }).click();
    await expect(page).toHaveURL(/app\/dashboard$/);
    await expect(page.getByRole('heading', { name: 'Browser Clinic', exact: true })).toBeVisible();
    await expect(page.getByText('No patients have been registered yet.')).toBeVisible();
    await expect(page.getByText(/Your trial ends in/)).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    await page.screenshot({ path: 'test-results/clinic-dashboard-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Open navigation' }).click();
    await expect(page.getByRole('navigation', { name: 'Clinic navigation' })).toBeVisible();
    await page.getByRole('navigation', { name: 'Clinic navigation' }).getByRole('link', { name: 'Patients', exact: true }).click();
    await expect(page.getByText('No patients registered yet.', { exact: true })).toBeVisible();
    await page.goBack();
    await expect(page).toHaveURL(/app\/dashboard$/);
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Browser Clinic', exact: true })).toBeVisible();
    await page.setViewportSize({ width: 820, height: 1180 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    await page.setViewportSize({ width: 1536, height: 1024 });
    await expect(page.getByText('No patients have been registered yet.')).toBeVisible();
    await page.screenshot({ path: 'test-results/clinic-dashboard-desktop.png', fullPage: true });
    await page.locator('.clinic-calendar a[aria-current="date"]').click();
    await expect(page).toHaveURL(/app\/appointments\?view=day&date=\d{4}-\d{2}-\d{2}$/);
    await page.goto('/app/pharmacy');
    await expect(page.getByRole('heading', { name: 'Access unavailable' })).toBeVisible();
    expect((await page.request.get('/api/v1/clinic/modules/pharmacy', { headers: { Accept: 'application/json', Origin: 'http://127.0.0.1:8011' } })).status()).toBe(403);
    await page.goto('/app/admin/clinics/1');
    await expect(page).toHaveURL(/app\/dashboard$/);
    await page.goto('/app/patients');
    await page.getByRole('link', { name: 'Add Patient', exact: false }).click();
    await expect(page.getByRole('heading', { name: 'Register New Patient' })).toBeVisible();
    await page.getByLabel('First name *', { exact: true }).fill('Amina');
    await page.getByLabel('Last name *', { exact: true }).fill('Hassan');
    await page.getByLabel('Gender *', { exact: true }).selectOption('female');
    await page.getByLabel('Date of birth', { exact: true }).fill('1992-04-15');
    await page.getByLabel('Phone', { exact: true }).fill('+252 612 345 678');
    await page.getByLabel('Known allergy', { exact: true }).fill('Penicillin');
    await page.getByRole('button', { name: 'Register Patient', exact: true }).click();
    await expect(page).toHaveURL(/app\/patients\/\d+\/overview$/);
    await expect(page.getByRole('heading', { name: 'Amina Hassan', exact: true })).toBeVisible();
    const patientUrl = page.url();
    await page.getByRole('link', { name: 'Edit Patient', exact: true }).click();
    await page.getByLabel('City', { exact: true }).fill('Hargeisa');
    await page.getByRole('button', { name: 'Save Changes' }).click();
    await expect(page.getByText('Hargeisa', { exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Medical History', exact: true }).click();
    await expect(page.getByText('Penicillin', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Add Condition' }).click();
    await page.getByLabel('Condition name *', { exact: true }).fill('Asthma');
    await page.getByRole('button', { name: 'Save Condition', exact: true }).click();
    await expect(page.getByText('Asthma', { exact: true })).toBeVisible();
    await page.getByRole('link', { name: 'Documents', exact: true }).click();
    await page.getByRole('button', { name: 'Upload Document' }).click();
    await page.getByLabel('Document title', { exact: true }).fill('Referral letter');
    await page.getByLabel('File', { exact: true }).setInputFiles({ name: 'referral.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nPatient test referral') });
    await page.getByRole('button', { name: 'Save Document' }).click();
    await expect(page.getByText('Referral letter', { exact: true })).toBeVisible();
    const downloadEvent = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download', exact: true }).click();
    expect((await downloadEvent).suggestedFilename()).toMatch(/patient-document-\d+\.pdf/);
    await page.goto('/app/patients');
    await page.getByLabel('Search patients').fill('Amina');
    await expect(page.locator('tbody').getByText('Amina Hassan')).toBeVisible();
    await page.screenshot({ path: 'test-results/patients-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.locator('.patient-mobile-list').getByText('Amina Hassan')).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    await page.screenshot({ path: 'test-results/patients-mobile.png', fullPage: true });
    await page.goto(patientUrl);
    await page.locator('.patient-actions summary').click();
    await page.getByRole('button', { name: 'Archive patient', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Archive Patient' }).click();
    await expect(page.locator('.patient-profile-header .badge')).toHaveText('archived');
    await page.locator('.patient-actions summary').click();
    await page.getByRole('button', { name: 'Restore patient', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Restore Patient' }).click();
    await expect(page.locator('.patient-profile-header .badge')).toHaveText('active');
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Amina Hassan', exact: true })).toBeVisible();
    await page.goto('/app/patients/create');
    await expect(page.getByLabel('Gender *', { exact: true }).locator('option')).toHaveText(['Select gender', 'Male', 'Female']);
    await page.getByLabel('First name *', { exact: true }).fill('Omar');
    await page.getByLabel('Last name *', { exact: true }).fill('Hassan');
    await page.getByLabel('Gender *', { exact: true }).selectOption('male');
    await page.getByRole('radio', { name: 'Age', exact: true }).check();
    await page.getByLabel('Age in years', { exact: true }).fill('34');
    await page.getByLabel('Phone', { exact: true }).fill('+252 612 345 678');
    await page.screenshot({ path: 'test-results/patient-age-form.png', fullPage: true });
    await page.getByRole('button', { name: 'Register Patient', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Possible matching patient found.' })).toBeVisible();
    await page.getByRole('button', { name: 'Continue Registration', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Omar Hassan', exact: true })).toBeVisible();
    await expect(page.getByText('34 years (estimated)', { exact: true })).toBeVisible();
    expect(errors).toEqual([]);
});

test('clinician registration, schedule, leave and responsive directory', async ({ page }) => {
    test.setTimeout(120000);
    const errors=[];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/app/login');
    await page.getByLabel('Email',{exact:true}).fill('browser-admin@example.test');
    await page.getByLabel('Password',{exact:true}).fill('BrowserTestPass123');
    await page.getByRole('button',{name:'Sign in'}).click();
    await expect(page.getByRole('heading',{name:/Welcome back/})).toBeVisible();
    const cookies=await page.context().cookies();
    const headers={'Accept':'application/json','Origin':'http://127.0.0.1:8011','X-XSRF-TOKEN':decodeURIComponent(cookies.find(c=>c.name==='XSRF-TOKEN').value)};
    const plan=await page.request.post('/api/v1/platform/plans',{headers,data:{name:'Clinician browser plan',slug:'clinician-browser',status:'active',price:0,currency:'USD',billing_period:'monthly',trial_days:14,branch_limit:3,member_limit:10,doctor_limit:5,features:{clinicians:true,multi_branch:true}}});
    expect(plan.ok(),await plan.text()).toBeTruthy();
    const tenant=await page.request.post('/api/v1/platform/tenants',{headers,data:{name:'Clinician Test Clinic',slug:'clinician-test',timezone:'Africa/Nairobi',plan_id:(await plan.json()).data.id,owner_name:'Clinician Owner',owner_email:'clinician-owner@example.test',owner_password:'DoctorOwnerPass123',owner_password_confirmation:'DoctorOwnerPass123'}});
    expect(tenant.ok(),await tenant.text()).toBeTruthy();
    await page.request.post('/logout',{headers});
    await page.goto('/app/login');
    await page.getByLabel('Email',{exact:true}).fill('clinician-owner@example.test');
    await page.getByLabel('Password',{exact:true}).fill('DoctorOwnerPass123');
    await page.getByRole('button',{name:'Sign in'}).click();
    await expect(page).toHaveURL(/app\/dashboard/);
    await page.goto('/app/doctors');
    await expect(page.getByText('No doctors or clinicians have been added yet.')).toBeVisible();
    await page.getByRole('link',{name:'Add Doctor',exact:false}).first().click();
    await page.getByLabel('First name *',{exact:true}).fill('Ahmed');
    await page.getByLabel('Last name *',{exact:true}).fill('Hassan');
    await page.getByLabel('Phone',{exact:true}).fill('+252 612 555 001');
    await page.getByLabel('Email',{exact:true}).fill('ahmed@example.test');
    await page.getByLabel('New specialty',{exact:true}).fill('General Practitioner');
    await page.getByRole('button',{name:'Add Specialty',exact:true}).click();
    await expect(page.getByRole('checkbox',{name:'General Practitioner'})).toBeChecked();
    await page.getByLabel('Qualification',{exact:true}).fill('MBBS');
    await page.getByRole('button',{name:'Create Doctor',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Ahmed Hassan',exact:true})).toBeVisible();
    const profile=page.url();
    await expect(page.getByText('DOC-00001',{exact:false}).first()).toBeVisible();
    await page.getByRole('link',{name:'Schedule',exact:true}).click();
    await page.getByRole('button',{name:'Edit Schedule',exact:true}).click();
    await page.getByRole('checkbox',{name:'Monday',exact:true}).check();
    await page.getByLabel('Monday start',{exact:true}).fill('08:00');
    await page.getByLabel('Monday end',{exact:true}).fill('16:00');
    await page.getByLabel('Monday break start',{exact:true}).fill('12:00');
    await page.getByLabel('Monday break end',{exact:true}).fill('13:00');
    await page.getByRole('button',{name:'Save Schedule',exact:true}).click();
    await expect(page.getByText('Working schedule saved.')).toBeVisible();
    await page.getByRole('button',{name:'Add Leave',exact:true}).click();
    await page.getByRole('dialog').getByRole('button',{name:'Save Leave',exact:true}).click();
    await expect(page.locator('.patient-profile-header').getByText('On Leave',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Cancel Leave',exact:true}).click();
    await page.getByRole('button',{name:'Confirm Cancellation',exact:true}).click();
    await expect(page.locator('.patient-profile-header').getByText('Available',{exact:true})).toBeVisible();
    await page.goto('/app/doctors');
    await page.getByLabel('Search clinicians').fill('Ahmed');
    await expect(page.locator('tbody').getByText('Ahmed Hassan',{exact:true})).toBeVisible();
    await expect(page.locator('.doctor-table').getByRole('link',{name:'View',exact:true})).toBeInViewport();
    await page.screenshot({path:'test-results/doctors-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await expect(page.locator('.patient-mobile-list').getByText('Ahmed Hassan',{exact:true})).toBeVisible();
    await expect.poll(async()=>page.locator('.clinic-sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
    await page.screenshot({path:'test-results/doctors-mobile.png',fullPage:true});
    await page.goto(profile);
    await page.locator('.patient-actions summary').click();
    await page.getByRole('button',{name:'Deactivate',exact:true}).click();
    await page.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click();
    await expect(page.locator('.patient-profile-header').getByText('Inactive',{exact:true})).toBeVisible();
    await page.reload();
    await expect(page.getByRole('heading',{name:'Ahmed Hassan',exact:true})).toBeVisible();
    expect(errors).toEqual([]);
});
