import { test, expect } from '@playwright/test';
import { spawnSync } from 'node:child_process';
import { env, php } from '../../playwright.config.js';

test.use({ actionTimeout: 15000 });

async function login(page, email) {
    await page.goto('/app/login');
    await page.getByLabel('Email address', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('BrowserTestPass123');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await expect(page).not.toHaveURL(/\/login$/);
}

test('platform support manages shared tenant tickets on desktop and mobile', async ({ page, browser }) => {
    test.setTimeout(180000);
    const fixture = spawnSync(php, ['tests/Browser/support-fixtures.php'], { env, encoding: 'utf8' });
    if (fixture.status !== 0) throw new Error(fixture.stderr || fixture.stdout);
    const tickets = JSON.parse(fixture.stdout);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await login(page, 'browser-admin@example.test');
    await page.getByRole('link', { name: 'Support Tickets', exact: true }).click();
    await expect(page).toHaveURL(/\/admin\/support-tickets$/);
    await expect(page.getByRole('heading', { name: 'Support Tickets', exact: true })).toBeVisible();
    await expect(page.locator('tbody tr')).toHaveCount(2);
    await expect(page.locator('.stat-card').filter({ hasText: 'Total Tickets' })).toContainText('2');
    await page.getByLabel('Search tickets', { exact: true }).fill('calendar');
    await expect(page.locator('tbody tr')).toHaveCount(1);
    await expect(page.locator('tbody')).toContainText('Booking calendar question');
    await page.getByRole('button', { name: 'Reset filters' }).click();
    await expect(page.locator('tbody tr')).toHaveCount(2);
    await page.getByRole('combobox', { name: 'Business Type', exact: true }).selectOption(String(tickets['support-salon'].business_type_id));
    await expect(page.locator('tbody tr')).toHaveCount(1);
    await expect(page.locator('tbody')).toContainText('Support Salon');
    await page.getByRole('button', { name: 'Reset filters' }).click();
    await page.getByRole('combobox', { name: 'Business / Tenant', exact: true }).selectOption(String(tickets['support-clinic'].tenant_id));
    await expect(page.locator('tbody tr')).toHaveCount(1);
    await page.getByRole('link', { name: 'View / Manage', exact: true }).filter({ visible: true }).click();
    await expect(page.getByRole('heading', { name: 'Cannot print an invoice' })).toBeVisible();
    await expect(page.getByText('Business User', { exact: true })).toBeVisible();
    await page.getByRole('combobox', { name: 'Priority', exact: true }).selectOption('Urgent');
    await page.getByRole('button', { name: 'Update Priority', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Ticket updated.');
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Waiting for Customer');
    await page.getByRole('button', { name: 'Update Status', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Update Status', exact: true })).toBeDisabled();
    await page.getByLabel('Message *', { exact: true }).fill('Please try the updated print button.');
    await page.getByLabel('Attachment (optional)').setInputFiles({ name: 'guide.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nSupport guide\n%%EOF') });
    await page.getByRole('button', { name: 'Send Reply', exact: true }).click();
    await expect(page.getByText('Please try the updated print button.', { exact: true })).toBeVisible();
    await expect(page.getByText('Platform Support / Admin', { exact: true })).toBeVisible();
    await expect(page.getByRole('link', { name: 'guide.pdf', exact: true }).first()).toBeVisible();
    const download = page.waitForEvent('download');
    await page.getByRole('link', { name: 'guide.pdf', exact: true }).first().click();
    expect((await download).suggestedFilename()).toBe('guide.pdf');
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Resolved');
    await page.getByRole('button', { name: 'Update Status', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Confirm Resolved' })).toBeVisible();
    await page.getByRole('button', { name: 'Confirm Resolved' }).click();
    await expect(page.locator('.page-header').getByText('Resolved', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Send Reply', exact: true })).toBeVisible();
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: 'test-results/support-desktop.png', fullPage: true });

    const tenantContext = await browser.newContext();
    const tenant = await tenantContext.newPage();
    tenant.on('pageerror', error => errors.push(error.message));
    await login(tenant, 'support-clinic@example.test');
    await tenant.goto(`/app/support/tickets/${tickets['support-clinic'].ticket_id}`);
    await expect(tenant.getByText('Please try the updated print button.', { exact: true })).toBeVisible();
    await expect(tenant.getByText('Platform Support / Admin', { exact: true })).toBeVisible();
    await expect(tenant.getByText('Resolved', { exact: true })).toBeVisible();
    await expect(tenant.getByText('Urgent', { exact: true })).toBeVisible();
    await tenant.getByPlaceholder('Add a reply to the support team').fill('The invoice now prints.');
    await tenant.getByRole('button', { name: 'Send Reply' }).click();
    await expect(tenant.getByText('The invoice now prints.', { exact: true })).toBeVisible();
    await page.reload();
    await expect(page.getByText('The invoice now prints.', { exact: true })).toBeVisible();
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Closed');
    await page.getByRole('button', { name: 'Update Status', exact: true }).click();
    await page.getByRole('button', { name: 'Confirm Closed' }).click();
    await expect(page.getByRole('button', { name: 'Send Reply' })).toHaveCount(0);
    await tenant.reload();
    await expect(tenant.getByRole('button', { name: 'Send Reply' })).toHaveCount(0);
    await tenant.goto('/app/admin/support-tickets');
    await expect(tenant).not.toHaveURL(/\/admin\/support-tickets$/);
    await tenantContext.close();

    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('link', { name: '← Support Tickets' }).click();
    await expect(page.getByRole('heading', { name: 'Cannot print an invoice' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/support-mobile.png', fullPage: true });
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('Closed');
    await expect(page.getByRole('heading', { name: 'Booking calendar question' })).toHaveCount(0);
    await page.getByRole('combobox', { name: 'Priority', exact: true }).selectOption('Urgent');
    await expect(page.getByRole('heading', { name: 'Cannot print an invoice' })).toBeVisible();
    await page.getByRole('link', { name: 'View / Manage' }).filter({ visible: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);

    const readerContext = await browser.newContext();
    const reader = await readerContext.newPage();
    await login(reader, 'support-reader@example.test');
    await reader.goto(`/app/admin/support-tickets/${tickets['support-salon'].ticket_id}`);
    await expect(reader.getByRole('heading', { name: 'Booking calendar question' })).toBeVisible();
    await expect(reader.getByRole('button', { name: 'Send Reply' })).toHaveCount(0);
    await expect(reader.getByRole('button', { name: 'Update Status' })).toHaveCount(0);
    await readerContext.close();
    expect(errors).toEqual([]);
});
