<script setup>
import { onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import api from '../../services/api';
import { useClinicContextStore } from '../../stores/clinicContext';
import FormErrors from '../../components/ui/FormErrors.vue';
const route=useRoute(),context=useClinicContextStore(),data=ref(null),error=ref(null),busy=ref(false),amount=ref(''),method=ref('cash'),reference=ref(''),methods=ref([]),key=ref(crypto.randomUUID());
async function load(page=1){error.value=null;data.value=null;try{const response=await api.get('/v1/billing/invoices'+(route.params.id?'/'+route.params.id:''),{params:{page},headers:context.headers()});data.value=response.data.data;methods.value=response.data.methods;method.value=methods.value[0]||'cash';if(route.params.id)amount.value=(Number(data.value.total)-Number(data.value.paid)).toFixed(2);}catch(e){error.value=e;}}
async function pay(){busy.value=true;error.value=null;try{await api.post('/v1/billing/invoices/'+route.params.id+'/payments',{amount:amount.value,method:method.value,reference:reference.value,idempotency_key:key.value},{headers:context.headers()});key.value=crypto.randomUUID();await load();}catch(e){error.value=e;}finally{busy.value=false;}}
onMounted(()=>load());watch(()=>route.params.id,()=>{key.value=crypto.randomUUID();load();});
</script>
<template><div><header class="patient-page-header"><div><RouterLink v-if="route.params.id" to="/app/billing/invoices">← Invoices</RouterLink><h1>{{ route.params.id?(data?.number||'Invoice'):'Billing' }}</h1><p>Service invoices and recorded payments.</p></div><RouterLink class="btn-secondary" to="/app/settings/billing">Billing Settings</RouterLink></header><FormErrors :error="error"/><template v-if="data"><div v-if="!route.params.id" class="clinic-panel overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Invoice</th><th>Client</th><th>Total</th><th>Paid</th><th>Status</th></tr></thead><tbody><tr v-for="row in data.data" :key="row.id"><td><RouterLink class="text-emerald-700" :to="'/app/billing/invoices/'+row.id">{{ row.number }}</RouterLink></td><td>{{ row.customer_name }}</td><td>{{ row.currency }} {{ Number(row.total).toFixed(2) }}</td><td>{{ Number(row.paid).toFixed(2) }}</td><td>{{ row.status }}</td></tr><tr v-if="!data.data.length"><td colspan="5">No invoices yet. Complete an appointment to create its invoice.</td></tr></tbody></table><div class="p-4 flex gap-3"><button class="btn-secondary" :disabled="data.current_page<=1" @click="load(data.current_page-1)">Previous</button><span>{{ data.current_page }} / {{ data.last_page }}</span><button class="btn-secondary" :disabled="data.current_page>=data.last_page" @click="load(data.current_page+1)">Next</button></div></div>
<template v-else><section class="clinic-panel p-6"><h2 class="text-lg font-semibold">{{ data.customer_name }}</h2><p>{{ data.status }}</p><table class="w-full mt-4"><thead><tr><th>Service</th><th>Quantity</th><th>Unit price</th><th>Amount</th></tr></thead><tbody><tr v-for="item in data.items" :key="item.id"><td>{{ item.description }}</td><td>{{ item.quantity }}</td><td>{{ Number(item.unit_price).toFixed(2) }}</td><td>{{ Number(item.amount).toFixed(2) }}</td></tr></tbody></table><p class="mt-4">Subtotal: {{ data.currency }} {{ Number(data.subtotal).toFixed(2) }}</p><p>Discount: {{ Number(data.discount).toFixed(2) }} · Tax: {{ Number(data.tax).toFixed(2) }}</p><p class="font-semibold">Total: {{ data.currency }} {{ Number(data.total).toFixed(2) }}</p><p>Paid: {{ Number(data.paid).toFixed(2) }} · Balance: {{ (Number(data.total)-Number(data.paid)).toFixed(2) }}</p></section>
<form v-if="context.can('billing.payments')&&data.status!=='paid'" class="clinic-panel p-6 mt-4" @submit.prevent="pay"><h2 class="font-semibold">Record Payment</h2><p class="hint">Record a payment already received. This does not charge a card or contact a payment gateway.</p><div class="form-grid mt-4"><label class="field">Amount<input v-model="amount" type="number" min="0.01" :max="Number(data.total)-Number(data.paid)" step="0.01" required></label><label class="field">Payment Method<select v-model="method" aria-label="Payment Method"><option v-for="m in methods" :key="m" :value="m">{{ m.replaceAll('_',' ') }}</option></select></label><label class="field">Reference<input v-model="reference" maxlength="255"></label></div><button class="btn mt-4" :disabled="busy">{{ busy?'Recording…':'Record Payment' }}</button></form><section class="clinic-panel p-6 mt-4"><h2 class="font-semibold">Payments</h2><p v-for="p in data.payments" :key="p.id" class="mt-2">{{ data.currency }} {{ Number(p.amount).toFixed(2) }} · {{ p.method.replaceAll('_',' ') }} · {{ new Date(p.paid_at).toLocaleString() }} · {{ p.reference }}</p><p v-if="!data.payments.length">No payments recorded.</p></section></template></template><p v-else-if="!error" role="status">Loading billing…</p></div></template>
<style scoped>th,td{text-align:left;padding:.8rem;border-bottom:1px solid #e2e8f0}</style>
