<script setup>
import { ref,reactive,onMounted } from 'vue';import { useRoute } from 'vue-router';import { doctorService } from '../../services/doctors';import { useClinicContextStore } from '../../stores/clinicContext';import { useDoctorStore } from '../../stores/doctors';import DoctorBadge from './DoctorBadge.vue';import FormErrors from '../ui/FormErrors.vue';
const context=useClinicContextStore(),store=useDoctorStore(),route=useRoute();const result=ref(null),busy=ref(false),error=ref(null),show=ref(route.query.leave==='1'&&context.can('doctors.leave.manage')),cancelling=ref(null);const form=reactive({branch_id:store.doctor.display_branch_id,start_date:context.data.today,end_date:context.data.today,reason:''});
async function load(page=1){busy.value=true;error.value=null;try{result.value=(await doctorService.leaves(store.doctor.id,page)).data.data;}catch(e){error.value=e;}finally{busy.value=false;}}
async function save(){busy.value=true;error.value=null;try{await doctorService.addLeave(store.doctor.id,{...form,branch_id:form.branch_id||null});show.value=false;await load();store.doctor=(await doctorService.get(store.doctor.id)).data.data;}catch(e){error.value=e;}finally{busy.value=false;}}
async function cancel(){busy.value=true;error.value=null;try{await doctorService.cancelLeave(store.doctor.id,cancelling.value.id);cancelling.value=null;await load();store.doctor=(await doctorService.get(store.doctor.id)).data.data;}catch(e){error.value=e;}finally{busy.value=false;}}onMounted(()=>load());
</script>
<template><section class="clinic-panel mt-5"><div class="clinic-card-heading"><div><h2>Leave</h2><p class="hint mt-2">Leave affects availability, not the clinician’s account status.</p></div><button v-if="context.can('doctors.leave.manage')" class="btn-secondary" @click="show=true">Add Leave</button></div><FormErrors v-if="!show && !cancelling" :error="error"/><button v-if="error && !show && !cancelling" class="btn-secondary" @click="load()">Try again</button><p v-if="busy && !show && !cancelling" class="empty-state">Loading leave...</p><template v-else-if="result"><div v-for="leave in result.data" :key="leave.id" class="patient-document-row"><div><strong>{{leave.start_date}} – {{leave.end_date}}</strong><p class="mt-2 text-sm text-slate-500">{{leave.branch_id?store.doctor.branches.find(b=>b.id===leave.branch_id)?.name:'All assigned branches'}}</p><p v-if="leave.reason" class="mt-2 text-sm text-slate-500">{{leave.reason}}</p></div><div class="flex items-center gap-3"><DoctorBadge :value="leave.status"/><button v-if="context.can('doctors.leave.manage') && !['cancelled','completed'].includes(leave.status) && (leave.branch_id || store.doctor.can_manage_branches)" class="btn-secondary" @click="cancelling=leave">Cancel Leave</button></div></div><p v-if="!result.data.length" class="empty-state">No leave records.</p><div v-if="result.last_page>1" class="patient-pagination"><button :disabled="result.current_page===1" @click="load(result.current_page-1)">Previous</button><span>{{result.current_page}} / {{result.last_page}}</span><button :disabled="result.current_page===result.last_page" @click="load(result.current_page+1)">Next</button></div></template></section>
<Teleport to="body"><div v-if="show" class="modal-backdrop"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="leave-title"><h2 id="leave-title" class="text-xl font-bold">Add Leave</h2><FormErrors class="mt-4" :error="error"/><form class="mt-5 grid gap-4" @submit.prevent="save"><label class="field">Branch<select v-model="form.branch_id"><option v-if="store.doctor.can_manage_branches" value="">All assigned branches</option><option v-for="b in store.doctor.branches" :key="b.id" :value="b.id">{{b.name}}</option></select></label><label class="field">Start date<input v-model="form.start_date" type="date" required></label><label class="field">End date<input v-model="form.end_date" type="date" :min="form.start_date" required></label><label class="field">Reason (optional)<textarea v-model="form.reason" maxlength="1000"></textarea></label><div class="flex justify-end gap-3"><button type="button" class="btn-secondary" :disabled="busy" @click="show=false">Cancel</button><button class="btn" :disabled="busy">Save Leave</button></div></form></section></div><div v-if="cancelling" class="modal-backdrop"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="cancel-leave-title"><h2 id="cancel-leave-title" class="text-xl font-bold">Cancel this leave?</h2><p class="my-4 text-slate-500">{{cancelling.start_date}} – {{cancelling.end_date}}. The clinician’s normal availability will apply again.</p><FormErrors :error="error"/><div class="mt-5 flex justify-end gap-3"><button class="btn-secondary" :disabled="busy" @click="cancelling=null">Keep Leave</button><button class="btn" :disabled="busy" @click="cancel">Confirm Cancellation</button></div></section></div></Teleport></template>
