<script setup>
import { onMounted, ref, watch } from 'vue';
import api from '../../../services/api';
import AppIcon from '../../../components/ui/AppIcon.vue';
import FormErrors from '../../../components/ui/FormErrors.vue';
import AuditEventBadge from '../../../components/admin/audit/AuditEventBadge.vue';
import AuditDetailDrawer from '../../../components/admin/audit/AuditDetailDrawer.vue';
import { auditLabel, subjectLabel } from '../../../config/auditEvents';

const events = ref([]), stats = ref({ total: 0, today: 0, security: 0, failed: 0 });
const facets = ref({ actions: [], actors: [], tenants: [], modules: [] });
const loading = ref(true), error = ref(null), selected = ref(null);
const page = ref(1), lastPage = ref(1), perPage = ref(25);
const search = ref(''), action = ref(''), module = ref(''), actor = ref(''), tenant = ref(''), dateRange = ref('30');
let timer;
const params = () => ({ search: search.value, action: action.value, module: module.value, actor_id: actor.value, tenant_id: tenant.value, date: dateRange.value, per_page: perPage.value, page: page.value });
async function load() { loading.value = true; error.value = null; try { const response = await api.get('/v1/platform/audits', { params: params() }); events.value = response.data.data; stats.value = response.data.stats; facets.value = response.data.filters; lastPage.value = response.data.meta.last_page; } catch (exception) { error.value = exception; } finally { loading.value = false; } }
watch([search, action, module, actor, tenant, dateRange, perPage], () => { page.value = 1; clearTimeout(timer); timer = setTimeout(load, 300); });
onMounted(load);
function reset() { search.value = ''; action.value = ''; module.value = ''; actor.value = ''; tenant.value = ''; dateRange.value = '30'; }
const format = value => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
async function exportCsv() { const response = await api.get('/v1/platform/audits/export', { params: params(), responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = 'audit-log.csv'; link.click(); URL.revokeObjectURL(url); }
</script>

<template><div>
<header class="page-header"><div><p class="eyebrow">Platform administration</p><h1>Audit Log</h1><p>Monitor administrative actions, security events and platform changes.</p></div><button class="btn-secondary" @click="exportCsv">Export CSV</button></header>
<FormErrors :error="error" />
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="stat-card stat-mint"><span class="stat-icon"><AppIcon name="plans" /></span><div><p>Total Events</p><strong>{{ stats.total }}</strong></div></article><article class="stat-card stat-blue"><span class="stat-icon text-blue-600"><AppIcon name="trial" /></span><div><p>Today's Events</p><strong>{{ stats.today }}</strong></div></article><article class="stat-card stat-rose"><span class="stat-icon text-rose-600"><AppIcon name="pause" /></span><div><p>Security Events</p><strong>{{ stats.security }}</strong></div></article><article class="stat-card stat-amber"><span class="stat-icon text-amber-600"><AppIcon name="trial" /></span><div><p>Failed / Suspicious</p><strong>{{ stats.failed }}</strong></div></article></div>
<section class="admin-card"><div class="audit-filters"><input v-model="search" class="filter-input" placeholder="Search events, users, clinics or resource ID..."><select v-model="action" class="filter-input"><option value="">All actions</option><option v-for="item in facets.actions" :key="item" :value="item">{{ auditLabel(item) }}</option></select><select v-model="module" class="filter-input"><option value="">All modules</option><option v-for="item in facets.modules" :key="item">{{ item }}</option></select><select v-model="actor" class="filter-input"><option value="">All actors</option><option v-for="item in facets.actors" :key="item.actor_id" :value="item.actor_id">{{ item.actor_name || 'Unknown' }}</option></select><select v-model="tenant" class="filter-input"><option value="">All clinics</option><option v-for="item in facets.tenants" :key="item.tenant_id" :value="item.tenant_id">{{ item.tenant_name }}</option></select><select v-model="dateRange" class="filter-input"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select><button class="btn-secondary" @click="reset">Reset</button></div>
<p v-if="loading" class="loading-state">Loading audit activity...</p><template v-else><div class="hidden table-wrap md:block"><table><thead><tr><th>Event</th><th>Description</th><th>Actor</th><th>Module</th><th>Target</th><th>Clinic</th><th>Date &amp; Time</th><th>IP Address</th><th>Actions</th></tr></thead><tbody><tr v-for="event in events" :key="event.id"><td><AuditEventBadge :event="event.action" /></td><td>{{ event.description || auditLabel(event.action) }}</td><td><p class="font-semibold">{{ event.actor_name || 'System' }}</p><p class="text-xs text-slate-500">{{ event.actor_email }}</p></td><td>{{ event.module || 'System' }}</td><td><p>{{ event.subject_name || subjectLabel(event.subject_type) }}</p><p class="text-xs text-slate-500">ID #{{ event.subject_id }}</p></td><td>{{ event.tenant_name || 'Platform' }}</td><td>{{ format(event.created_at) }}</td><td>{{ event.ip_address || 'Not recorded' }}</td><td><button class="btn-secondary" @click="selected = event">View</button></td></tr></tbody></table></div>
<div class="space-y-3 md:hidden"><article v-for="event in events" :key="event.id" class="rounded-xl border p-4"><div class="flex justify-between gap-2"><AuditEventBadge :event="event.action" /><button class="back-link" @click="selected = event">View</button></div><p class="mt-3 font-semibold">{{ event.actor_name || 'System' }}</p><p class="text-sm text-slate-500">{{ event.subject_name || subjectLabel(event.subject_type) }} · {{ format(event.created_at) }}</p></article></div><p v-if="!events.length" class="empty-state">No activity matches your current filters.</p><div class="mt-5 flex flex-wrap items-center justify-between gap-3"><span class="text-sm text-slate-500">Page {{ page }} of {{ lastPage }}</span><div class="flex gap-2"><select v-model="perPage" class="compact-select"><option :value="25">25 rows</option><option :value="50">50 rows</option><option :value="100">100 rows</option></select><button class="btn-secondary" :disabled="page <= 1" @click="page--; load()">Previous</button><button class="btn-secondary" :disabled="page >= lastPage" @click="page++; load()">Next</button></div></div></template></section>
<AuditDetailDrawer :event="selected" @close="selected = null" />
</div></template>
