<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClinicController;
use App\Http\Controllers\PlatformController;
use App\Http\Controllers\PlatformRoleController;
use App\Http\Controllers\PlatformUserController;
use App\Http\Controllers\ProvisioningController;
use App\Http\Controllers\SystemSettingsController;
use Illuminate\Support\Facades\Route;

Route::get('v1/public/settings', [SystemSettingsController::class, 'publicSettings']);

Route::middleware('auth:sanctum')->prefix('v1')->group(function () {
    Route::get('clinic/context', [\App\Http\Controllers\ClinicDashboardController::class, 'context'])->middleware('platform.available');
    Route::get('session', [AuthController::class, 'session']);
    Route::post('session/clinic', [AuthController::class, 'select']);
    Route::prefix('platform')->middleware('platform')->group(function () {
        Route::prefix('support-tickets')->middleware('platform.permission:support_tickets.view')->group(function () {
            Route::get('/', [\App\Http\Controllers\PlatformSupportTicketController::class, 'index']);
            Route::get('stats', [\App\Http\Controllers\PlatformSupportTicketController::class, 'stats']);
            Route::get('options', [\App\Http\Controllers\PlatformSupportTicketController::class, 'options']);
            Route::get('{ticket}', [\App\Http\Controllers\PlatformSupportTicketController::class, 'show'])->whereNumber('ticket');
            Route::post('{ticket}/reply', [\App\Http\Controllers\PlatformSupportTicketController::class, 'reply'])->whereNumber('ticket')->middleware('platform.permission:support_tickets.reply');
            Route::put('{ticket}/{field}', [\App\Http\Controllers\PlatformSupportTicketController::class, 'update'])->whereNumber('ticket')->whereIn('field', ['status', 'priority', 'category']);
            Route::get('{ticket}/attachments/{attachment}/download', [\App\Http\Controllers\PlatformSupportTicketController::class, 'download'])->whereNumber(['ticket', 'attachment']);
        });
        Route::get('dashboard', [PlatformController::class, 'dashboard'])->middleware('platform.permission:platform.dashboard.view');
        Route::get('subscriptions', [PlatformController::class, 'subscriptions'])->middleware('platform.permission:subscriptions.view');
        Route::get('users', [PlatformUserController::class, 'index']);
        Route::post('users', [PlatformUserController::class, 'store']);
        Route::get('users/{user}', [PlatformUserController::class, 'show']);
        Route::put('users/{user}', [PlatformUserController::class, 'update']);
        Route::get('roles', [PlatformUserController::class, 'roles']);
        Route::post('roles', [PlatformRoleController::class, 'store']);
        Route::put('roles/{role}', [PlatformRoleController::class, 'update']);
        Route::get('permissions', [PlatformRoleController::class, 'permissions']);
        Route::get('businesses/next-code', [\App\Http\Controllers\BusinessCodeController::class, 'preview'])->middleware('platform.permission:tenants.manage');
        Route::get('businesses/code-examples', [\App\Http\Controllers\BusinessCodeController::class, 'examples'])->middleware('platform.permission:settings.view');
        Route::get('tenants', [PlatformController::class, 'tenants'])->middleware('platform.permission:tenants.view');
        Route::get('business-types', [PlatformController::class, 'businessTypes'])->middleware('platform.permission:tenants.view');
        Route::post('business-types', [PlatformController::class, 'storeBusinessType'])->middleware('platform.permission:tenants.manage');
        Route::get('business-types/{businessType}', [PlatformController::class, 'showBusinessType'])->middleware('platform.permission:tenants.view');
        Route::put('business-types/{businessType}', [PlatformController::class, 'updateBusinessType'])->middleware('platform.permission:tenants.manage');
        Route::post('business-types/{businessType}/activate', [PlatformController::class, 'activateBusinessType'])->middleware('platform.permission:tenants.manage');
        Route::post('business-types/{businessType}/deactivate', [PlatformController::class, 'deactivateBusinessType'])->middleware('platform.permission:tenants.manage');
        Route::post('tenants', [PlatformController::class, 'store'])->middleware('platform.permission:tenants.manage');
        Route::get('tenants/{tenant}', [PlatformController::class, 'show'])->middleware('platform.permission:tenants.view');
        Route::patch('tenants/{tenant}', [PlatformController::class, 'update'])->middleware('platform.permission:tenants.manage');
        Route::get('tenants/{tenant}/audits', [PlatformController::class, 'tenantAudits'])->middleware('platform.permission:tenants.view');
        Route::get('tenants/{tenant}/subscription', [PlatformController::class, 'subscription'])->middleware('platform.permission:subscriptions.view');
        Route::put('tenants/{tenant}/subscription', [PlatformController::class, 'updateSubscription'])->middleware('platform.permission:subscriptions.manage');
        Route::get('plans', [PlatformController::class, 'plans'])->middleware('platform.permission:plans.view');
        Route::post('plans', [PlatformController::class, 'storePlan'])->middleware('platform.permission:plans.manage');
        Route::get('plans/{plan}', [PlatformController::class, 'showPlan'])->middleware('platform.permission:plans.view');
        Route::put('plans/{plan}', [PlatformController::class, 'updatePlan'])->middleware('platform.permission:plans.manage');
        Route::delete('plans/{plan}', [PlatformController::class, 'destroyPlan'])->middleware('platform.permission:plans.manage');
        Route::get('plans/{plan}/subscriptions', [PlatformController::class, 'planSubscriptions'])->middleware('platform.permission:plans.view');
        Route::get('plans/{plan}/audits', [PlatformController::class, 'planAudits'])->middleware('platform.permission:plans.view');
        Route::get('audits', [PlatformController::class, 'audits'])->middleware('platform.permission:audit.view');
        Route::get('audits/export', [PlatformController::class, 'exportAudits'])->middleware('platform.permission:audit.view');
        Route::get('settings', [SystemSettingsController::class, 'index'])->middleware('platform.permission:settings.view');
        Route::put('settings/{section}', [SystemSettingsController::class, 'update'])->whereIn('section',['general','branding','localization','email','notifications','security','backup'])->middleware('platform.permission:settings.update');
        Route::post('settings/email/test', [SystemSettingsController::class, 'testEmail'])->middleware('platform.permission:settings.update');
        Route::get('settings/system-info', [SystemSettingsController::class, 'systemInfo'])->middleware('platform.permission:settings.view');
        Route::post('settings/cache/clear', [SystemSettingsController::class, 'clearCache'])->middleware('platform.permission:settings.maintenance');
        Route::post('settings/maintenance', [SystemSettingsController::class, 'maintenance'])->middleware('platform.permission:settings.maintenance');
        Route::get('tenants/{tenant}/members', [ProvisioningController::class, 'members'])->middleware('platform.permission:tenants.view');
        Route::post('tenants/{tenant}/members', [ProvisioningController::class, 'addMember'])->middleware('platform.permission:tenants.manage');
        Route::patch('tenants/{tenant}/members/{member}', [ProvisioningController::class, 'updateMember'])->whereNumber('member')->middleware('platform.permission:tenants.manage');
        Route::get('tenants/{tenant}/branches', [ProvisioningController::class, 'branches'])->middleware('platform.permission:tenants.view');
        Route::post('tenants/{tenant}/branches', [ProvisioningController::class, 'addBranch'])->middleware('platform.permission:tenants.manage');
    });
    Route::prefix('billing')->middleware(['platform.available','tenant'])->group(function () {
        Route::get('invoices', [\App\Http\Controllers\BillingController::class, 'index']);
        Route::get('invoices/{id}', [\App\Http\Controllers\BillingController::class, 'show'])->whereNumber('id');
        Route::get('invoices/{id}/print', [\App\Http\Controllers\BillingController::class, 'invoicePrint'])->whereNumber('id');
        Route::get('payments/{id}/receipt', [\App\Http\Controllers\BillingController::class, 'receipt'])->whereNumber('id');
        Route::post('invoices/{id}/payments', [\App\Http\Controllers\BillingController::class, 'payment'])->whereNumber('id');
    });
    Route::prefix('salon')->middleware(['platform.available','tenant'])->group(function () {
        Route::get('billing/sources', [\App\Http\Controllers\BillingController::class, 'salonSources']);
        Route::get('booking-history/{kind}/{id}', [\App\Http\Controllers\SalonBookingController::class, 'history'])->whereIn('kind',['clients','stylists','services'])->whereNumber('id');
        Route::get('appointments/options', [\App\Http\Controllers\SalonBookingController::class, 'options']);
        Route::get('appointments/clients', [\App\Http\Controllers\SalonBookingController::class, 'clients']);
        Route::get('appointments/available-slots', [\App\Http\Controllers\SalonBookingController::class, 'slots']);
        Route::get('appointments/available-stylists', [\App\Http\Controllers\SalonBookingController::class, 'availableStylists']);
        Route::get('appointments', [\App\Http\Controllers\SalonBookingController::class, 'index']);
        Route::post('appointments', [\App\Http\Controllers\SalonBookingController::class, 'store']);
        Route::get('appointments/{id}', [\App\Http\Controllers\SalonBookingController::class, 'show'])->whereNumber('id');
        Route::put('appointments/{id}', [\App\Http\Controllers\SalonBookingController::class, 'update'])->whereNumber('id');
        Route::post('appointments/{id}/reschedule', [\App\Http\Controllers\SalonBookingController::class, 'reschedule'])->whereNumber('id');
        Route::get('appointments/{id}/activity', [\App\Http\Controllers\SalonBookingController::class, 'activity'])->whereNumber('id');
        Route::post('appointments/{id}/invoice', [\App\Http\Controllers\BillingController::class, 'fromSalon'])->whereNumber('id');
        Route::post('appointments/{id}/{action}', [\App\Http\Controllers\SalonBookingController::class, 'status'])->whereNumber('id')->whereIn('action', array_keys(config('salon_booking.actions')));
        Route::get('location-hours', [\App\Http\Controllers\SalonScheduleController::class, 'hours']);
        Route::put('location-hours', [\App\Http\Controllers\SalonScheduleController::class, 'saveHours']);
        Route::get('stylists/{stylist}/schedule', [\App\Http\Controllers\SalonScheduleController::class, 'schedule'])->whereNumber('stylist');
        Route::put('stylists/{stylist}/schedule', [\App\Http\Controllers\SalonScheduleController::class, 'saveSchedule'])->whereNumber('stylist');
        Route::get('stylists/{stylist}/time-off', [\App\Http\Controllers\SalonScheduleController::class, 'timeOff'])->whereNumber('stylist');
        Route::post('stylists/{stylist}/time-off', [\App\Http\Controllers\SalonScheduleController::class, 'createTimeOff'])->whereNumber('stylist');
        Route::post('stylists/{stylist}/time-off/{id}/cancel', [\App\Http\Controllers\SalonScheduleController::class, 'cancelTimeOff'])->whereNumber(['stylist','id']);
        foreach (['clients'=>\App\Http\Controllers\ClientController::class,'stylists'=>\App\Http\Controllers\SalonStaffController::class,'services'=>\App\Http\Controllers\SalonServiceController::class,'service-categories'=>\App\Http\Controllers\SalonServiceCategoryController::class] as $path=>$controller) {
            Route::get($path.'/options',[$controller,'options']);
            Route::get($path,[$controller,'index']);
            Route::post($path,[$controller,'store']);
            Route::get($path.'/{record}',[$controller,'show'])->whereNumber('record');
            Route::put($path.'/{record}',[$controller,'update'])->whereNumber('record');
            if (in_array($path,['clients','services'])) Route::post($path.'/{record}/archive',[$controller,'archive'])->whereNumber('record');
        }
    });
    Route::prefix('clinic')->middleware(['platform.available','tenant'])->group(function () {


        Route::get('settings', [\App\Http\Controllers\ClinicSettingsController::class,'index']);
        Route::get('settings/preview/{kind}', [\App\Http\Controllers\ClinicSettingsController::class,'preview'])->whereIn('kind',['prescription','invoice','receipt']);
        Route::get('settings/subscription', [\App\Http\Controllers\ClinicSettingsController::class,'subscription']);
        Route::get('settings/branches', [\App\Http\Controllers\ClinicSettingsBranchController::class,'index']);
        Route::post('settings/branches', [\App\Http\Controllers\ClinicSettingsBranchController::class,'store']);
        Route::put('settings/branches/{branch}', [\App\Http\Controllers\ClinicSettingsBranchController::class,'update'])->whereNumber('branch');
        Route::post('settings/branding', [\App\Http\Controllers\ClinicBrandingController::class,'store']);
        Route::get('settings/branding/{asset}', [\App\Http\Controllers\ClinicBrandingController::class,'show'])->whereIn('asset',['logo','small_logo','receipt_logo','prescription_logo','invoice_logo','stamp']);
        Route::put('settings/{section}', [\App\Http\Controllers\ClinicSettingsController::class,'update'])->whereIn('section',array_keys(config('clinic_settings')));
        Route::get('prescriptions', [\App\Http\Controllers\PrescriptionQueryController::class, 'index']);
        Route::get('prescriptions/stats', [\App\Http\Controllers\PrescriptionQueryController::class, 'stats']);
        Route::get('prescriptions/options', [\App\Http\Controllers\PrescriptionQueryController::class, 'options']);
        Route::get('prescriptions/patients', [\App\Http\Controllers\PrescriptionQueryController::class, 'patients']);
        Route::get('prescriptions/appointments', [\App\Http\Controllers\PrescriptionQueryController::class, 'appointments']);
        Route::get('medications/search', [\App\Http\Controllers\PrescriptionQueryController::class, 'medications']);
        Route::post('medications', [\App\Http\Controllers\PrescriptionQueryController::class, 'storeMedication']);
        Route::post('prescriptions', [\App\Http\Controllers\PrescriptionController::class, 'store']);
        Route::get('prescriptions/{prescription}', [\App\Http\Controllers\PrescriptionController::class, 'show'])->whereNumber('prescription');
        Route::put('prescriptions/{prescription}', [\App\Http\Controllers\PrescriptionController::class, 'update'])->whereNumber('prescription');
        Route::post('prescriptions/{prescription}/cancel', [\App\Http\Controllers\PrescriptionController::class, 'cancel'])->whereNumber('prescription');
        Route::post('prescriptions/{prescription}/send-to-pharmacy', [\App\Http\Controllers\PrescriptionController::class, 'send'])->whereNumber('prescription');
        Route::post('prescriptions/{prescription}/dispense', [\App\Http\Controllers\PrescriptionController::class, 'dispense'])->whereNumber('prescription');
        Route::get('prescriptions/{prescription}/activity', [\App\Http\Controllers\PrescriptionController::class, 'activity'])->whereNumber('prescription');
        Route::get('prescriptions/{prescription}/print', \App\Http\Controllers\PrescriptionPrintController::class)->whereNumber('prescription');
        Route::get('appointments/options', [\App\Http\Controllers\AppointmentController::class, 'options']);
        Route::get('appointments/patients', [\App\Http\Controllers\AppointmentController::class, 'patients']);
        Route::get('appointments/calendar', [\App\Http\Controllers\AppointmentCalendarController::class, 'calendar']);
        Route::get('appointments/today', [\App\Http\Controllers\AppointmentCalendarController::class, 'today']);
        Route::get('appointments/hours', [\App\Http\Controllers\AppointmentAvailabilityController::class, 'hours']);
        Route::get('appointment-types', [\App\Http\Controllers\AppointmentController::class, 'types']);
        Route::post('appointment-types', [\App\Http\Controllers\AppointmentController::class, 'storeType']);
        Route::get('appointments', [\App\Http\Controllers\AppointmentCalendarController::class, 'index']);
        Route::post('appointments', [\App\Http\Controllers\AppointmentController::class, 'store']);
        Route::get('appointments/{appointment}', [\App\Http\Controllers\AppointmentController::class, 'show'])->whereNumber('appointment');
        Route::put('appointments/{appointment}', [\App\Http\Controllers\AppointmentController::class, 'update'])->whereNumber('appointment');
        Route::post('appointments/{appointment}/reschedule', [\App\Http\Controllers\AppointmentController::class, 'reschedule'])->whereNumber('appointment')->name('appointments.reschedule');
        Route::get('appointments/{appointment}/activity', [\App\Http\Controllers\AppointmentController::class, 'activity'])->whereNumber('appointment');
        Route::post('appointments/{appointment}/invoice', [\App\Http\Controllers\BillingController::class, 'fromClinic'])->whereNumber('appointment');
        Route::post('appointments/{appointment}/{action}', [\App\Http\Controllers\AppointmentController::class, 'status'])->whereNumber('appointment')->whereIn('action',array_keys(config('appointments.actions')));
        Route::get('doctors/{doctor}/available-slots', [\App\Http\Controllers\AppointmentAvailabilityController::class, 'slots'])->whereNumber('doctor');
        Route::get('doctors/options', [\App\Http\Controllers\DoctorController::class, 'options']);
        Route::get('specialties', [\App\Http\Controllers\DoctorController::class, 'specialties']);
        Route::post('specialties', [\App\Http\Controllers\DoctorController::class, 'specialty']);
        Route::get('doctors', [\App\Http\Controllers\DoctorController::class, 'index']);
        Route::post('doctors', [\App\Http\Controllers\DoctorController::class, 'store']);
        Route::get('doctors/{doctor}', [\App\Http\Controllers\DoctorController::class, 'show'])->whereNumber('doctor');
        Route::put('doctors/{doctor}', [\App\Http\Controllers\DoctorController::class, 'update'])->whereNumber('doctor');
        Route::post('doctors/{doctor}/{action}', [\App\Http\Controllers\DoctorController::class, 'status'])->whereNumber('doctor')->whereIn('action',['activate','deactivate']);
        Route::get('doctors/{doctor}/schedule', [\App\Http\Controllers\DoctorScheduleController::class, 'index'])->whereNumber('doctor');
        Route::put('doctors/{doctor}/schedule', [\App\Http\Controllers\DoctorScheduleController::class, 'update'])->whereNumber('doctor');
        Route::get('doctors/{doctor}/leaves', [\App\Http\Controllers\DoctorLeaveController::class, 'index'])->whereNumber('doctor');
        Route::post('doctors/{doctor}/leaves', [\App\Http\Controllers\DoctorLeaveController::class, 'store'])->whereNumber('doctor');
        Route::post('doctors/{doctor}/leaves/{leave}/cancel', [\App\Http\Controllers\DoctorLeaveController::class, 'cancel'])->whereNumber(['doctor','leave']);
        Route::get('doctors/{doctor}/activity', [\App\Http\Controllers\DoctorController::class, 'activity'])->whereNumber('doctor');
        Route::get('patients', [\App\Http\Controllers\PatientController::class, 'index']);
        Route::post('patients', [\App\Http\Controllers\PatientController::class, 'store']);
        Route::get('patients/{patient}', [\App\Http\Controllers\PatientController::class, 'show'])->whereNumber('patient');
        Route::put('patients/{patient}', [\App\Http\Controllers\PatientController::class, 'update'])->whereNumber('patient');
        Route::post('patients/{patient}/{action}', [\App\Http\Controllers\PatientController::class, 'status'])->whereNumber('patient')->whereIn('action', ['archive', 'restore']);
        Route::get('patients/{patient}/activity', [\App\Http\Controllers\PatientController::class, 'activity'])->whereNumber('patient');
        Route::get('patients/{patient}/{kind}', [\App\Http\Controllers\PatientHistoryController::class, 'index'])->whereNumber('patient')->whereIn('kind', ['allergies', 'conditions']);
        Route::post('patients/{patient}/{kind}', [\App\Http\Controllers\PatientHistoryController::class, 'save'])->whereNumber('patient')->whereIn('kind', ['allergies', 'conditions']);
        Route::put('patients/{patient}/{kind}/{entry}', [\App\Http\Controllers\PatientHistoryController::class, 'save'])->whereNumber(['patient', 'entry'])->whereIn('kind', ['allergies', 'conditions']);
        Route::get('patients/{patient}/documents', [\App\Http\Controllers\PatientDocumentController::class, 'index'])->whereNumber('patient');
        Route::post('patients/{patient}/documents', [\App\Http\Controllers\PatientDocumentController::class, 'store'])->whereNumber('patient');
        Route::get('patients/{patient}/documents/{document}/download', [\App\Http\Controllers\PatientDocumentController::class, 'download'])->whereNumber(['patient', 'document']);
        Route::post('patients/{patient}/documents/{document}/archive', [\App\Http\Controllers\PatientDocumentController::class, 'archive'])->whereNumber(['patient', 'document']);
        Route::get('staff/options', [\App\Http\Controllers\ClinicStaffController::class, 'options']);
        Route::get('staff/stats', [\App\Http\Controllers\ClinicStaffController::class, 'stats']);
        Route::get('staff', [\App\Http\Controllers\ClinicStaffController::class, 'index']);
        Route::post('staff', [\App\Http\Controllers\ClinicStaffController::class, 'store']);
        Route::get('staff/{staff}', [\App\Http\Controllers\ClinicStaffController::class, 'show'])->whereNumber('staff');
        Route::put('staff/{staff}', [\App\Http\Controllers\ClinicStaffController::class, 'update'])->whereNumber('staff');
        Route::post('staff/{staff}/activate', [\App\Http\Controllers\ClinicStaffController::class, 'activate'])->whereNumber('staff');
        Route::post('staff/{staff}/deactivate', [\App\Http\Controllers\ClinicStaffController::class, 'deactivate'])->whereNumber('staff');
        Route::post('staff/{staff}/reset-password', [\App\Http\Controllers\ClinicStaffController::class, 'resetPassword'])->whereNumber('staff');
        Route::get('support/articles', [\App\Http\Controllers\SupportController::class, 'articles']);
        Route::get('support/articles/{slug}', [\App\Http\Controllers\SupportController::class, 'article']);
        Route::get('support/search', [\App\Http\Controllers\SupportController::class, 'search']);
        Route::get('support/faqs', [\App\Http\Controllers\SupportController::class, 'faqs']);
        Route::get('support/tickets', [\App\Http\Controllers\SupportController::class, 'tickets']);
        Route::post('support/tickets', [\App\Http\Controllers\SupportController::class, 'storeTicket']);
        Route::get('support/tickets/{ticket}', [\App\Http\Controllers\SupportController::class, 'ticket'])->whereNumber('ticket');
        Route::post('support/tickets/{ticket}/reply', [\App\Http\Controllers\SupportController::class, 'reply'])->whereNumber('ticket');
        Route::post('support/tickets/{ticket}/attachments', [\App\Http\Controllers\SupportController::class, 'attachments'])->whereNumber('ticket');
        Route::get('support/tickets/{ticket}/attachments/{attachment}/download', [\App\Http\Controllers\SupportController::class, 'downloadAttachment'])->whereNumber(['ticket', 'attachment']);
        Route::get('support/system-info', [\App\Http\Controllers\SupportController::class, 'systemInfo']);
        Route::get('dashboard', [\App\Http\Controllers\ClinicDashboardController::class, 'dashboard']);
        Route::get('reports/overview', [\App\Http\Controllers\ReportsController::class, 'overview']);
        Route::get('reports/patients', [\App\Http\Controllers\ReportsController::class, 'patients']);
        Route::get('reports/appointments', [\App\Http\Controllers\ReportsController::class, 'appointments']);
        Route::get('reports/clinical', [\App\Http\Controllers\ReportsController::class, 'clinical']);
        Route::get('reports/doctors', [\App\Http\Controllers\ReportsController::class, 'doctors']);
        Route::get('reports/prescriptions', [\App\Http\Controllers\ReportsController::class, 'prescriptions']);
        Route::get('reports/financial', [\App\Http\Controllers\ReportsController::class, 'financial']);
        Route::get('reports/branches', [\App\Http\Controllers\ReportsController::class, 'branches']);
        Route::post('branch', [\App\Http\Controllers\ClinicDashboardController::class, 'switchBranch']);
        Route::get('modules/{module}', [\App\Http\Controllers\ClinicDashboardController::class, 'module'])->whereIn('module', array_keys(config('clinic.modules')));
        Route::get('branches', [ClinicController::class, 'branches']);
        Route::get('branches/{branch}', [ClinicController::class, 'branch'])->whereNumber('branch');
    });
});
