<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClinicController;
use App\Http\Controllers\PlatformController;
use App\Http\Controllers\PlatformRoleController;
use App\Http\Controllers\PlatformUserController;
use App\Http\Controllers\ProvisioningController;
use App\Http\Controllers\SystemSettingsController;
use Illuminate\Support\Facades\Route;

Route::get('v1/public/settings', [SystemSettingsController::class, 'publicSettings']);

Route::middleware('auth:sanctum')->prefix('v1')->group(function () {
    Route::get('clinic/context', [\App\Http\Controllers\ClinicDashboardController::class, 'context'])->middleware('platform.available');
    Route::get('session', [AuthController::class, 'session']);
    Route::post('session/clinic', [AuthController::class, 'select']);
    Route::prefix('platform')->middleware('platform')->group(function () {
        Route::get('dashboard', [PlatformController::class, 'dashboard'])->middleware('platform.permission:platform.dashboard.view');
        Route::get('subscriptions', [PlatformController::class, 'subscriptions'])->middleware('platform.permission:subscriptions.view');
        Route::get('users', [PlatformUserController::class, 'index']);
        Route::post('users', [PlatformUserController::class, 'store']);
        Route::get('users/{user}', [PlatformUserController::class, 'show']);
        Route::put('users/{user}', [PlatformUserController::class, 'update']);
        Route::get('roles', [PlatformUserController::class, 'roles']);
        Route::post('roles', [PlatformRoleController::class, 'store']);
        Route::put('roles/{role}', [PlatformRoleController::class, 'update']);
        Route::get('permissions', [PlatformRoleController::class, 'permissions']);
        Route::get('tenants', [PlatformController::class, 'tenants'])->middleware('platform.permission:tenants.view');
        Route::post('tenants', [PlatformController::class, 'store'])->middleware('platform.permission:tenants.manage');
        Route::get('tenants/{tenant}', [PlatformController::class, 'show'])->middleware('platform.permission:tenants.view');
        Route::patch('tenants/{tenant}', [PlatformController::class, 'update'])->middleware('platform.permission:tenants.manage');
        Route::get('tenants/{tenant}/audits', [PlatformController::class, 'tenantAudits'])->middleware('platform.permission:tenants.view');
        Route::get('tenants/{tenant}/subscription', [PlatformController::class, 'subscription'])->middleware('platform.permission:subscriptions.view');
        Route::put('tenants/{tenant}/subscription', [PlatformController::class, 'updateSubscription'])->middleware('platform.permission:subscriptions.manage');
        Route::get('plans', [PlatformController::class, 'plans'])->middleware('platform.permission:plans.view');
        Route::post('plans', [PlatformController::class, 'storePlan'])->middleware('platform.permission:plans.manage');
        Route::get('plans/{plan}', [PlatformController::class, 'showPlan'])->middleware('platform.permission:plans.view');
        Route::put('plans/{plan}', [PlatformController::class, 'updatePlan'])->middleware('platform.permission:plans.manage');
        Route::delete('plans/{plan}', [PlatformController::class, 'destroyPlan'])->middleware('platform.permission:plans.manage');
        Route::get('plans/{plan}/subscriptions', [PlatformController::class, 'planSubscriptions'])->middleware('platform.permission:plans.view');
        Route::get('plans/{plan}/audits', [PlatformController::class, 'planAudits'])->middleware('platform.permission:plans.view');
        Route::get('audits', [PlatformController::class, 'audits'])->middleware('platform.permission:audit.view');
        Route::get('audits/export', [PlatformController::class, 'exportAudits'])->middleware('platform.permission:audit.view');
        Route::get('settings', [SystemSettingsController::class, 'index'])->middleware('platform.permission:settings.view');
        Route::put('settings/{section}', [SystemSettingsController::class, 'update'])->whereIn('section',['general','branding','localization','email','notifications','security','backup'])->middleware('platform.permission:settings.update');
        Route::post('settings/email/test', [SystemSettingsController::class, 'testEmail'])->middleware('platform.permission:settings.update');
        Route::get('settings/system-info', [SystemSettingsController::class, 'systemInfo'])->middleware('platform.permission:settings.view');
        Route::post('settings/cache/clear', [SystemSettingsController::class, 'clearCache'])->middleware('platform.permission:settings.maintenance');
        Route::post('settings/maintenance', [SystemSettingsController::class, 'maintenance'])->middleware('platform.permission:settings.maintenance');
        Route::get('tenants/{tenant}/members', [ProvisioningController::class, 'members'])->middleware('platform.permission:tenants.view');
        Route::post('tenants/{tenant}/members', [ProvisioningController::class, 'addMember'])->middleware('platform.permission:tenants.manage');
        Route::patch('tenants/{tenant}/members/{member}', [ProvisioningController::class, 'updateMember'])->whereNumber('member')->middleware('platform.permission:tenants.manage');
        Route::get('tenants/{tenant}/branches', [ProvisioningController::class, 'branches'])->middleware('platform.permission:tenants.view');
        Route::post('tenants/{tenant}/branches', [ProvisioningController::class, 'addBranch'])->middleware('platform.permission:tenants.manage');
    });
    Route::prefix('clinic')->middleware(['platform.available','tenant'])->group(function () {
        Route::get('appointments/options', [\App\Http\Controllers\AppointmentController::class, 'options']);
        Route::get('appointments/patients', [\App\Http\Controllers\AppointmentController::class, 'patients']);
        Route::get('appointments/calendar', [\App\Http\Controllers\AppointmentCalendarController::class, 'calendar']);
        Route::get('appointments/today', [\App\Http\Controllers\AppointmentCalendarController::class, 'today']);
        Route::get('appointments/hours', [\App\Http\Controllers\AppointmentAvailabilityController::class, 'hours']);
        Route::get('appointment-types', [\App\Http\Controllers\AppointmentController::class, 'types']);
        Route::post('appointment-types', [\App\Http\Controllers\AppointmentController::class, 'storeType']);
        Route::get('appointments', [\App\Http\Controllers\AppointmentCalendarController::class, 'index']);
        Route::post('appointments', [\App\Http\Controllers\AppointmentController::class, 'store']);
        Route::get('appointments/{appointment}', [\App\Http\Controllers\AppointmentController::class, 'show'])->whereNumber('appointment');
        Route::put('appointments/{appointment}', [\App\Http\Controllers\AppointmentController::class, 'update'])->whereNumber('appointment');
        Route::post('appointments/{appointment}/reschedule', [\App\Http\Controllers\AppointmentController::class, 'reschedule'])->whereNumber('appointment')->name('appointments.reschedule');
        Route::get('appointments/{appointment}/activity', [\App\Http\Controllers\AppointmentController::class, 'activity'])->whereNumber('appointment');
        Route::post('appointments/{appointment}/{action}', [\App\Http\Controllers\AppointmentController::class, 'status'])->whereNumber('appointment')->whereIn('action',array_keys(config('appointments.actions')));
        Route::get('doctors/{doctor}/available-slots', [\App\Http\Controllers\AppointmentAvailabilityController::class, 'slots'])->whereNumber('doctor');
        Route::get('doctors/options', [\App\Http\Controllers\DoctorController::class, 'options']);
        Route::get('specialties', [\App\Http\Controllers\DoctorController::class, 'specialties']);
        Route::post('specialties', [\App\Http\Controllers\DoctorController::class, 'specialty']);
        Route::get('doctors', [\App\Http\Controllers\DoctorController::class, 'index']);
        Route::post('doctors', [\App\Http\Controllers\DoctorController::class, 'store']);
        Route::get('doctors/{doctor}', [\App\Http\Controllers\DoctorController::class, 'show'])->whereNumber('doctor');
        Route::put('doctors/{doctor}', [\App\Http\Controllers\DoctorController::class, 'update'])->whereNumber('doctor');
        Route::post('doctors/{doctor}/{action}', [\App\Http\Controllers\DoctorController::class, 'status'])->whereNumber('doctor')->whereIn('action',['activate','deactivate']);
        Route::get('doctors/{doctor}/schedule', [\App\Http\Controllers\DoctorScheduleController::class, 'index'])->whereNumber('doctor');
        Route::put('doctors/{doctor}/schedule', [\App\Http\Controllers\DoctorScheduleController::class, 'update'])->whereNumber('doctor');
        Route::get('doctors/{doctor}/leaves', [\App\Http\Controllers\DoctorLeaveController::class, 'index'])->whereNumber('doctor');
        Route::post('doctors/{doctor}/leaves', [\App\Http\Controllers\DoctorLeaveController::class, 'store'])->whereNumber('doctor');
        Route::post('doctors/{doctor}/leaves/{leave}/cancel', [\App\Http\Controllers\DoctorLeaveController::class, 'cancel'])->whereNumber(['doctor','leave']);
        Route::get('doctors/{doctor}/activity', [\App\Http\Controllers\DoctorController::class, 'activity'])->whereNumber('doctor');
        Route::get('patients', [\App\Http\Controllers\PatientController::class, 'index']);
        Route::post('patients', [\App\Http\Controllers\PatientController::class, 'store']);
        Route::get('patients/{patient}', [\App\Http\Controllers\PatientController::class, 'show'])->whereNumber('patient');
        Route::put('patients/{patient}', [\App\Http\Controllers\PatientController::class, 'update'])->whereNumber('patient');
        Route::post('patients/{patient}/{action}', [\App\Http\Controllers\PatientController::class, 'status'])->whereNumber('patient')->whereIn('action', ['archive', 'restore']);
        Route::get('patients/{patient}/activity', [\App\Http\Controllers\PatientController::class, 'activity'])->whereNumber('patient');
        Route::get('patients/{patient}/{kind}', [\App\Http\Controllers\PatientHistoryController::class, 'index'])->whereNumber('patient')->whereIn('kind', ['allergies', 'conditions']);
        Route::post('patients/{patient}/{kind}', [\App\Http\Controllers\PatientHistoryController::class, 'save'])->whereNumber('patient')->whereIn('kind', ['allergies', 'conditions']);
        Route::put('patients/{patient}/{kind}/{entry}', [\App\Http\Controllers\PatientHistoryController::class, 'save'])->whereNumber(['patient', 'entry'])->whereIn('kind', ['allergies', 'conditions']);
        Route::get('patients/{patient}/documents', [\App\Http\Controllers\PatientDocumentController::class, 'index'])->whereNumber('patient');
        Route::post('patients/{patient}/documents', [\App\Http\Controllers\PatientDocumentController::class, 'store'])->whereNumber('patient');
        Route::get('patients/{patient}/documents/{document}/download', [\App\Http\Controllers\PatientDocumentController::class, 'download'])->whereNumber(['patient', 'document']);
        Route::post('patients/{patient}/documents/{document}/archive', [\App\Http\Controllers\PatientDocumentController::class, 'archive'])->whereNumber(['patient', 'document']);
        Route::get('dashboard', [\App\Http\Controllers\ClinicDashboardController::class, 'dashboard']);
        Route::post('branch', [\App\Http\Controllers\ClinicDashboardController::class, 'switchBranch']);
        Route::get('modules/{module}', [\App\Http\Controllers\ClinicDashboardController::class, 'module'])->whereIn('module', array_keys(config('clinic.modules')));
        Route::get('branches', [ClinicController::class, 'branches']);
        Route::get('branches/{branch}', [ClinicController::class, 'branch'])->whereNumber('branch');
    });
});
