<script setup>
import { reactive, ref, onMounted } from 'vue';
import { patientService } from '../../services/patients';
import { useClinicContextStore } from '../../stores/clinicContext';
import { usePatientStore } from '../../stores/patients';
import FormErrors from '../ui/FormErrors.vue';
const props = defineProps({ kind: String, patient: Object });
const context = useClinicContextStore(), store = usePatientStore();
const result = ref(null), error = ref(null), busy = ref(false), editing = ref(false), entry = ref(null);
const form = reactive({});
const allergy = props.kind === 'allergies';
async function load(page = 1) { error.value = null; busy.value = true; try { result.value = (await patientService.entries(props.patient.id, props.kind, page)).data.data; } catch (e) { error.value = e; } finally { busy.value = false; } }
function edit(item = null) { entry.value = item?.id || null; Object.keys(form).forEach(key => delete form[key]); Object.assign(form, allergy ? { allergen: item?.allergen || '', reaction: item?.reaction || '', severity: item?.severity || '', status: item?.status || 'active', notes: item?.notes || '' } : { condition_name: item?.condition_name || '', diagnosed_date: item?.diagnosed_date || '', status: item?.status || 'active', notes: item?.notes || '' }); editing.value = true; }
async function save() { busy.value = true; error.value = null; try { await patientService.saveEntry(props.patient.id, props.kind, entry.value, form); editing.value = false; await load(); if (allergy) store.patient = (await patientService.get(props.patient.id)).data.data; } catch (e) { error.value = e; } finally { busy.value = false; } }
onMounted(() => load());
</script>
<template><section class="clinic-panel"><div class="clinic-card-heading"><h2>{{ allergy ? 'Allergies' : 'Medical conditions' }}</h2><button v-if="context.can('patients.medical_history.update') && patient.status !== 'archived'" class="btn-secondary" @click="edit()">{{ allergy ? 'Add Allergy' : 'Add Condition' }}</button></div><FormErrors :error="error" /><button v-if="error && !editing" class="btn-secondary" @click="load()">Try again</button>
    <form v-if="editing" class="patient-history-form" @submit.prevent="save"><label class="field">{{ allergy ? 'Allergen' : 'Condition name' }} *<input v-model="form[allergy ? 'allergen' : 'condition_name']" required maxlength="150"></label><label v-if="allergy" class="field">Reaction<input v-model="form.reaction" maxlength="255"></label><label v-if="allergy" class="field">Severity<select v-model="form.severity"><option value="">Not specified</option><option>mild</option><option>moderate</option><option>severe</option></select></label><label v-else class="field">Diagnosed date<input v-model="form.diagnosed_date" type="date" :max="context.data.today"></label><label class="field">Status<select v-model="form.status"><option v-for="value in allergy ? ['active','inactive'] : ['active','resolved','historical']" :key="value">{{ value }}</option></select></label><label class="field">Notes<textarea v-model="form.notes" maxlength="3000"></textarea></label><div class="flex gap-3"><button class="btn" :disabled="busy">Save {{ allergy ? 'Allergy' : 'Condition' }}</button><button class="btn-secondary" type="button" @click="editing = false">Cancel</button></div></form>
    <p v-if="busy" class="empty-state" role="status">Loading...</p><template v-else-if="result"><article v-for="item in result.data" :key="item.id" class="patient-history-item"><div class="flex items-center justify-between gap-3"><strong>{{ allergy ? item.allergen : item.condition_name }}</strong><span class="badge capitalize" :class="item.severity === 'severe' && item.status === 'active' ? 'badge-rose' : 'bg-slate-100 text-slate-600'">{{ item.severity || item.status }}</span></div><p v-if="allergy" class="mt-2 text-sm text-slate-500 capitalize">{{ item.reaction || 'Reaction not recorded' }} · {{ item.status }}</p><p v-else class="mt-2 text-sm text-slate-500">{{ item.diagnosed_date || 'Diagnosis date not recorded' }}</p><p class="mt-2 whitespace-pre-wrap text-slate-600">{{ item.notes }}</p><button v-if="context.can('patients.medical_history.update') && patient.status !== 'archived'" class="back-link mt-3" @click="edit(item)">Edit {{ allergy ? 'allergy' : 'condition' }}</button></article><p v-if="!result.data.length" class="empty-state">{{ allergy ? 'No known allergies recorded.' : 'No medical conditions recorded.' }}</p><div v-if="result.last_page > 1" class="patient-pagination"><button :disabled="result.current_page === 1" @click="load(result.current_page - 1)">Previous</button><span>{{ result.current_page }} / {{ result.last_page }}</span><button :disabled="result.current_page === result.last_page" @click="load(result.current_page + 1)">Next</button></div></template>
</section></template>
