<script setup>
import PatientStatus from './PatientStatus.vue';
import PatientActions from './PatientActions.vue';
defineProps({ patients: Array }); defineEmits(['changed']);
const initials = name => name.split(' ').filter(Boolean).map(s => s[0]).slice(0, 2).join('');
const date = value => new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
</script>
<template>
    <div class="patient-desktop-table"><table><thead><tr><th>Patient</th><th>Patient ID</th><th>Gender / Age</th><th>Phone</th><th>Blood Group</th><th>Registered</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="(patient, index) in patients" :key="patient.id"><td><RouterLink class="patient-identity" :to="`/app/patients/${patient.id}`"><span class="patient-initials" :class="['blue','violet','mint','amber'][index % 4]">{{ initials(patient.full_name) }}</span><strong>{{ patient.full_name }}</strong></RouterLink></td><td>{{ patient.patient_number }}</td><td class="capitalize">{{ patient.gender }} · {{ patient.age === null ? 'Age unknown' : `${patient.age} yrs` }}</td><td>{{ patient.phone || '—' }}</td><td>{{ patient.blood_group || '—' }}</td><td>{{ date(patient.registered_at) }}</td><td><PatientStatus :status="patient.status" /></td><td><div class="flex items-center gap-3"><RouterLink class="btn-secondary" :to="`/app/patients/${patient.id}`">View</RouterLink><PatientActions :patient="patient" @changed="$emit('changed')" /></div></td></tr></tbody></table></div>
    <div class="patient-mobile-list"><article v-for="patient in patients" :key="patient.id"><div class="flex items-center justify-between gap-3"><RouterLink :to="`/app/patients/${patient.id}`" class="patient-identity"><span class="patient-initials mint">{{ initials(patient.full_name) }}</span><span><strong>{{ patient.full_name }}</strong><small>{{ patient.patient_number }}</small></span></RouterLink><PatientActions :patient="patient" @changed="$emit('changed')" /></div><p class="mt-4 capitalize text-slate-500">{{ patient.gender }} · {{ patient.age === null ? 'Age unknown' : `${patient.age} years` }}</p><p class="mt-2 text-slate-500">{{ patient.phone || 'No phone recorded' }}</p><div class="mt-4 flex justify-between"><PatientStatus :status="patient.status" /><RouterLink class="text-teal-700 font-semibold" :to="`/app/patients/${patient.id}`">View profile →</RouterLink></div></article></div>
</template>
