<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue';
import api from '../../../services/api';
import FormErrors from '../../../components/ui/FormErrors.vue';

const tabs=['General','Branding','Localization','Email','Notifications','Security','Storage & Backup','Maintenance'];
const keys=['general','branding','localization','email','notifications','security','backup','maintenance'];
const active=ref('general'), settings=reactive({}), original=ref('{}'), plans=ref([]), info=ref({}), loading=ref(true), saving=ref(false), error=ref(null), notice=ref(''), testAddress=ref(''), testBusy=ref(false), previews=reactive({});
const maintenanceMessage=ref('The platform is undergoing scheduled maintenance. Please try again shortly.');
const form=computed(()=>settings[active.value]||{});
const dirty=computed(()=>active.value!=='maintenance'&&JSON.stringify(settings[active.value]||{})!==original.value);
function snapshot(){original.value=JSON.stringify(settings[active.value]||{})}
function switchTab(key){if(dirty.value&&!confirm('Discard unsaved changes?'))return;active.value=key;snapshot()}
function discard(){settings[active.value]=JSON.parse(original.value)}
async function load(){try{const response=await api.get('/v1/platform/settings');Object.assign(settings,response.data.data);plans.value=response.data.plans;active.value='general';snapshot();const system=await api.get('/v1/platform/settings/system-info');info.value=system.data.data}catch(e){error.value=e}finally{loading.value=false}}
async function save(){saving.value=true;error.value=null;try{let payload=settings[active.value];if(active.value==='branding'){const data=new FormData();Object.entries(payload).forEach(([key,value])=>{if(value!==null&&value!==undefined&&typeof value!=='object')data.append(key,value)});Object.entries(previews).forEach(([key,item])=>{if(item.file)data.append(key,item.file)});data.append('_method','PUT');const response=await api.post('/v1/platform/settings/branding',data);settings.branding=response.data.data}else{const response=await api.put('/v1/platform/settings/'+active.value,payload);settings[active.value]=response.data.data}snapshot();notice.value='Settings updated successfully.';setTimeout(()=>notice.value='',3500)}catch(e){error.value=e}finally{saving.value=false}}
function chooseAsset(key,event){const file=event.target.files[0];if(!file)return;previews[key]={file,url:URL.createObjectURL(file)}}
async function testEmail(){testBusy.value=true;error.value=null;try{const response=await api.post('/v1/platform/settings/email/test',{email:testAddress.value});notice.value=response.data.message}catch(e){error.value=e}finally{testBusy.value=false}}
async function clearCache(cache){if(!confirm(`Clear the ${cache} cache?`))return;try{const response=await api.post('/v1/platform/settings/cache/clear',{cache});notice.value=response.data.message}catch(e){error.value=e}}
async function setMaintenance(enabled){if(!confirm(`${enabled?'Enable':'Disable'} maintenance mode?`))return;try{const response=await api.post('/v1/platform/settings/maintenance',{enabled,message:maintenanceMessage.value});info.value.maintenance=response.data.data.maintenance;notice.value=response.data.message}catch(e){error.value=e}}
function leave(event){if(dirty.value){event.preventDefault();event.returnValue=''}}
watch(active,snapshot);onMounted(()=>{load();window.addEventListener('beforeunload',leave)});onBeforeUnmount(()=>window.removeEventListener('beforeunload',leave));
</script>

<template><div><header class="page-header"><div><p class="eyebrow">Platform administration</p><h1>System Settings</h1><p>Configure global platform preferences, security and services.</p></div></header><div v-if="notice" class="mb-5 rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{{notice}}</div><FormErrors :error="error"/><p v-if="loading" class="loading-state">Loading system settings...</p><template v-else><nav class="settings-tabs" aria-label="System setting sections"><button v-for="(tab,index) in tabs" :key="tab" :class="active===keys[index]?'active':''" @click="switchTab(keys[index])">{{tab}}</button></nav>
<section v-if="active==='general'" class="settings-card"><header><h2>General Settings</h2><p>Basic platform configuration and clinic registration defaults.</p></header><div class="form-grid"><label class="field">Platform Name<input v-model="form.platform_name" required></label><label class="field">Platform URL<input v-model="form.platform_url" type="url" required></label><label class="field">Company / Organization Name<input v-model="form.organization_name"></label><label class="field">Support Email<input v-model="form.support_email" type="email"></label><label class="field">Support Phone<input v-model="form.support_phone"></label><label class="field">Default Trial Days<input v-model.number="form.default_trial_days" type="number" min="0"></label><label class="field">Default Plan<select v-model="form.default_plan_id"><option :value="null">No default plan</option><option v-for="plan in plans" :key="plan.id" :value="plan.id">{{plan.name}}</option></select></label><label class="field">Platform Status<select v-model="form.platform_status"><option value="active">Active</option><option value="maintenance">Maintenance</option></select></label></div><label class="toggle-row"><input v-model="form.registration_enabled" type="checkbox"> Allow new clinic registration</label></section>
<section v-else-if="active==='branding'" class="settings-card"><header><h2>Branding</h2><p>Images are stored on the public application disk and used across the platform.</p></header><div class="form-grid"><label class="field">Platform Display Name<input v-model="form.display_name"></label><label class="field">Footer Text<input v-model="form.footer_text"></label><label v-for="asset in [['logo','Platform Logo'],['small_logo','Small Logo / Icon'],['favicon','Favicon'],['login_logo','Login Page Logo']]" :key="asset[0]" class="upload-field"><span>{{asset[1]}}</span><img v-if="previews[asset[0]]?.url||form[asset[0]]" :src="previews[asset[0]]?.url||form[asset[0]]" :alt="asset[1]+' preview'"><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,image/x-icon" @change="chooseAsset(asset[0],$event)"><small>PNG, JPG, WebP or SVG. Maximum 2 MB.</small></label></div></section>
<section v-else-if="active==='localization'" class="settings-card"><header><h2>Localization</h2><p>Defaults for new platform activity. Existing financial records retain their stored currency.</p></header><div class="form-grid"><label class="field">Default Timezone<input v-model="form.timezone"></label><label class="field">Default Currency<input v-model="form.currency" maxlength="3"></label><label class="field">Currency Symbol<input v-model="form.currency_symbol"></label><label class="field">Date Format<select v-model="form.date_format"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label class="field">Time Format<select v-model="form.time_format"><option value="12">12 Hour</option><option value="24">24 Hour</option></select></label><label class="field">Default Language<select v-model="form.language"><option value="en">English</option></select></label></div></section>
<section v-else-if="active==='email'" class="settings-card"><header><h2>Email Configuration</h2><p>SMTP secrets are encrypted and are never returned by the API.</p></header><div class="form-grid"><label class="field">Mail Driver<select v-model="form.mailer"><option value="smtp">SMTP</option><option value="log">Log (development)</option><option value="array">Array (testing)</option></select></label><label class="field">From Name<input v-model="form.from_name"></label><label class="field">From Email<input v-model="form.from_email" type="email"></label><template v-if="form.mailer==='smtp'"><label class="field">SMTP Host<input v-model="form.smtp_host"></label><label class="field">SMTP Port<input v-model.number="form.smtp_port" type="number"></label><label class="field">SMTP Username<input v-model="form.smtp_username"></label><label class="field">SMTP Password<input v-model="form.smtp_password" type="password" autocomplete="new-password"><small class="hint">Leave the masked value unchanged to keep the stored secret.</small></label><label class="field">Encryption<select v-model="form.encryption"><option value="tls">TLS</option><option value="ssl">SSL</option></select></label></template></div><div class="test-panel"><label class="field">Send a real test email<input v-model="testAddress" type="email" placeholder="recipient@example.com"></label><button class="btn-secondary" :disabled="testBusy||!testAddress" @click="testEmail">{{testBusy?'Sending...':'Test Email Configuration'}}</button></div></section>
<section v-else-if="active==='notifications'" class="settings-card"><header><h2>Notification Settings</h2><p>Global delivery capabilities and notification categories.</p></header><div class="settings-columns"><div><h3>Email</h3><label v-for="item in [['email_enabled','Enable Email Notifications'],['appointment_enabled','Appointment Notifications'],['subscription_enabled','Subscription Notifications'],['trial_expiry_enabled','Trial Expiry Notifications'],['security_enabled','Security Notifications']]" :key="item[0]" class="toggle-row"><input v-model="form[item[0]]" type="checkbox">{{item[1]}}</label></div><div><h3>SMS</h3><label class="toggle-row"><input v-model="form.sms_enabled" type="checkbox">Enable SMS</label><template v-if="form.sms_enabled"><label class="field">Provider<input v-model="form.sms_provider"></label><label class="field">Sender ID<input v-model="form.sms_sender_id"></label><label class="field">Provider Secret<input v-model="form.sms_secret" type="password"></label></template><p v-else class="hint">SMS delivery remains disabled until a provider is configured.</p></div><div><h3>WhatsApp</h3><label class="toggle-row"><input v-model="form.whatsapp_enabled" type="checkbox">Enable WhatsApp</label><template v-if="form.whatsapp_enabled"><label class="field">Provider<input v-model="form.whatsapp_provider"></label><label class="field">Provider Secret<input v-model="form.whatsapp_secret" type="password"></label></template><p v-else class="hint">WhatsApp delivery remains disabled until a provider is configured.</p></div></div></section>
<section v-else-if="active==='security'" class="settings-card"><header><h2>Security</h2><p>Platform authentication and session policy.</p></header><div class="form-grid"><label class="field">Minimum Password Length<input v-model.number="form.minimum_password_length" type="number" min="8"></label><label class="field">Session Lifetime (minutes)<input v-model.number="form.session_lifetime" type="number" min="15"></label><label class="field">Maximum Login Attempts<input v-model.number="form.login_attempt_limit" type="number" min="3"></label><label class="field">Account Lockout (minutes)<input v-model.number="form.lockout_duration" type="number" min="1"></label></div><div class="settings-columns"><div><h3>Password Requirements</h3><label v-for="item in [['require_uppercase','Require uppercase'],['require_lowercase','Require lowercase'],['require_number','Require number'],['require_special','Require special character']]" :key="item[0]" class="toggle-row"><input v-model="form[item[0]]" type="checkbox">{{item[1]}}</label></div><div><h3>Administrator Security</h3><label class="toggle-row"><input v-model="form.admin_2fa_required" type="checkbox">Require Platform Admin 2FA</label><label class="toggle-row"><input v-model="form.security_notifications" type="checkbox">Security Notifications</label></div></div></section>
<section v-else-if="active==='backup'" class="settings-card"><header><h2>Storage &amp; Backup</h2><p>Storage defaults and backup scheduling policy.</p></header><div class="form-grid"><label class="field">Storage Driver<select v-model="form.storage_driver"><option value="local">Local</option><option value="s3">S3 / Compatible Storage</option></select></label><template v-if="form.storage_driver==='s3'"><label class="field">Access Key<input v-model="form.s3_key"></label><label class="field">Secret Key<input v-model="form.s3_secret" type="password"><small class="hint">The stored secret is encrypted and never exposed.</small></label><label class="field">Region<input v-model="form.s3_region"></label><label class="field">Bucket<input v-model="form.s3_bucket"></label><label class="field">Compatible Endpoint<input v-model="form.s3_endpoint" type="url"></label></template><label class="field">Backup Frequency<select v-model="form.backup_frequency"><option value="disabled">Disabled</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><label class="field">Backup Retention<select v-model.number="form.backup_retention"><option :value="7">7 days</option><option :value="14">14 days</option><option :value="30">30 days</option><option :value="90">90 days</option></select></label></div><label class="toggle-row"><input v-model="form.automatic_backups" type="checkbox">Automatic Backups</label><div class="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Backup runner unavailable.</strong> Scheduling can be configured, but manual execution is hidden until a queue-backed backup package is installed.</div></section>
<section v-else class="space-y-6"><section class="settings-card"><header><h2>System Information</h2><p>Non-sensitive runtime information.</p></header><dl class="detail-list"><div v-for="(value,key) in info" :key="key"><dt>{{key.replaceAll('_',' ')}}</dt><dd>{{value===false?'Online':value===true?'Maintenance':value}}</dd></div></dl></section><section class="settings-card"><header><h2>Maintenance Mode</h2><p>Clinic APIs return a maintenance response while platform administration remains available for recovery.</p></header><label class="field">Maintenance Message<textarea v-model="maintenanceMessage" rows="3"></textarea></label><button v-if="!info.maintenance" class="btn-danger mt-5" @click="setMaintenance(true)">Enable Maintenance Mode</button><button v-else class="btn mt-5" @click="setMaintenance(false)">Disable Maintenance Mode</button></section><section class="settings-card"><header><h2>Cache Management</h2><p>Only approved Laravel cache operations are available.</p></header><div class="flex flex-wrap gap-3"><button v-for="cache in ['application','config','route','view']" :key="cache" class="btn-secondary" @click="clearCache(cache)">Clear {{cache}} cache</button></div></section><section class="settings-card border-rose-200"><header><h2 class="text-rose-800">Danger Zone</h2><p>Database deletion, reset, and arbitrary command execution are intentionally unavailable.</p></header></section></section>
<div v-if="active!=='maintenance'" class="sticky-actions mt-6"><button class="btn-secondary" :disabled="!dirty||saving" @click="discard">Discard Changes</button><button class="btn" :disabled="!dirty||saving" @click="save">{{saving?'Saving...':'Save Changes'}}</button></div></template></div></template>
