<!doctype html><html lang="en"><head><meta charset="utf-8"><title>{{ $p->prescription_number }}</title><style>
body{font:14px/1.6 Arial,sans-serif;color:#14233f;box-sizing:border-box;max-width:900px;margin:32px auto;padding:12mm}header{border-bottom:3px solid #005c5d;padding-bottom:20px}h1{color:#005c5d;margin:0}table{width:100%;border-collapse:collapse;margin:24px 0}th,td{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #ddd}small{display:block}.signature{margin-top:70px;border-top:1px solid #777;width:260px}footer{margin-top:40px;color:#666}@page{size:A4;margin:8mm}@media print{body{max-width:none;margin:0;padding:12mm}tr{break-inside:avoid}button{display:none}}
</style></head><body><header><h1>{{ $clinic->name }}</h1><div>{{ $p->branch->name }}</div><div>{{ $clinic->address ?? '' }} {{ $clinic->phone ?? '' }} {{ $clinic->email ?? '' }}</div><small>Afri Clinic · Prescription</small></header>
<h2>{{ $p->prescription_number }} · {{ $p->prescription_date->format('M j, Y') }}</h2><p>{{ config('prescriptions.statuses.'.$p->status) }}</p>
<p><strong>Patient: {{ $p->patient->full_name }}</strong><br>{{ $p->patient->patient_number }} · {{ ucfirst($p->patient->gender) }} · {{ $p->patient->age ?? '—' }} years</p>
<p><strong>Prescriber: {{ $p->doctor->full_name }}</strong><br>{{ $p->doctor->specialties->pluck('name')->join(', ') }}<br>License: {{ $p->doctor->license_number ?? '—' }}</p>
@if($p->diagnosis)<p>Clinical indication: {{ $p->diagnosis }}</p>@endif
<table><thead><tr><th>Medication</th><th>Directions</th><th>Duration</th><th>Quantity</th></tr></thead><tbody>@foreach($p->items as $item)<tr><td><strong>{{ $item->medication_name }}</strong><small>{{ $item->strength }} {{ $item->dosage_form }}</small></td><td>{{ $item->dose }} · {{ config('prescriptions.routes.'.$item->route) }}<br>{{ $item->frequency==='custom' ? $item->custom_frequency : config('prescriptions.frequencies.'.$item->frequency) }}<small>{{ $item->instructions }}</small></td><td>{{ $item->duration }}</td><td>{{ $item->quantity ?? '—' }}</td></tr>@endforeach</tbody></table>
@if($p->notes)<p>{{ $p->notes }}</p>@endif
<div class="signature">Prescriber signature / stamp</div><footer>{{ $clinic->name }} · {{ $p->branch->name }}<br>Please follow the medication instructions provided by your clinician.</footer></body></html>
