<?php

return [
    'clinic' => [
        'code_prefix' => 'CLN',
        'name' => 'Healthcare / Clinic',
        'category' => 'healthcare',
        'subtitle' => 'Healthcare',
        'settings_label' => 'Clinic Settings',
        'dashboard_profile_key' => 'clinic',
        'navigation_profile_key' => 'clinic',
        'labels' => [
            'workspace' => 'clinic', 'information' => 'Clinic Information',
            'customer' => 'Patient',
            'customers' => 'Patients',
            'staff' => 'Staff',
            'booking' => 'Appointment',
            'bookings' => 'Appointments',
            'service' => 'Consultation',
            'services' => 'Consultations',
        ],
        'modules' => [
            'dashboard' => true, 'settings' => true, 'support' => true,
            'patients' => true,
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => true,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => true, 'appointment_engine' => true,
            'prescriptions' => true,
            'pharmacy' => true,
            'facilities' => false,
            'events' => false,
        ],
        'navigation_profile' => [
            ['label' => 'Dashboard', 'items' => ['dashboard']],
            ['label' => 'Patient Care', 'items' => ['patients', 'appointments']],
            ['label' => 'Clinical', 'items' => ['doctors', 'consultations', 'prescriptions']],
            ['label' => 'Operations', 'items' => ['pharmacy', 'billing']],
            ['label' => 'Analytics', 'items' => ['reports']],
            ['label' => 'Administration', 'items' => ['staff', 'support', 'settings']],
        ],

    ],
    'dental' => [
        'code_prefix' => 'DEN',
        'name' => 'Dental Clinic',
        'category' => 'healthcare',
        'subtitle' => 'Dental Healthcare',
        'settings_label' => 'Clinic Settings',
        'dashboard_profile_key' => 'clinic',
        'navigation_profile_key' => 'clinic',
        'labels' => [
            'workspace' => 'clinic', 'information' => 'Clinic Information',
            'customer' => 'Patient',
            'customers' => 'Patients',
            'staff' => 'Staff',
            'booking' => 'Appointment',
            'bookings' => 'Appointments',
            'service' => 'Dental Consultation',
            'services' => 'Dental Consultations',
        ],
        'modules' => [
            'dashboard' => true, 'settings' => true, 'support' => true,
            'patients' => true,
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => true,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => true, 'appointment_engine' => true,
            'prescriptions' => true,
            'pharmacy' => false,
            'facilities' => false,
            'events' => false,
        ],
        'navigation_profile' => [
            ['label' => 'Dashboard', 'items' => ['dashboard']],
            ['label' => 'Patient Care', 'items' => ['patients', 'appointments']],
            ['label' => 'Clinical', 'items' => ['doctors', 'consultations', 'prescriptions']],
            ['label' => 'Operations', 'items' => ['billing']],
            ['label' => 'Analytics', 'items' => ['reports']],
            ['label' => 'Administration', 'items' => ['staff', 'support', 'settings']],
        ],

    ],
    'beauty-salon' => [
        'code_prefix' => 'SAL',
        'name' => 'Beauty Salon',
        'category' => 'beauty',
        'subtitle' => 'Beauty & Wellness',
        'settings_label' => 'Salon Settings',
        'dashboard_profile_key' => 'beauty-salon',
        'navigation_profile_key' => 'beauty-salon',
        'labels' => [
            'workspace' => 'salon', 'information' => 'Salon Information',
            'customer' => 'Client',
            'customers' => 'Clients',
            'staff' => 'Stylist',
            'staff_plural' => 'Stylists',
            'booking' => 'Appointment',
            'bookings' => 'Appointments',
            'service' => 'Service',
            'services' => 'Services',
        ],
        'modules' => [
            'salon_core' => true, 'appointment_engine' => true,
            'dashboard' => true, 'settings' => true, 'support' => true,
            'patients' => false,
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => true,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => false,
            'prescriptions' => false,
            'pharmacy' => false,
            'facilities' => false,
            'events' => false,
        ],
        'navigation_profile' => [
            ['label' => 'Dashboard', 'items' => ['dashboard']],
            ['label' => 'Clients', 'items' => ['clients','appointments']],
            ['label' => 'Services', 'items' => ['stylists','services']],
            ['label' => 'Operations', 'items' => ['billing']],
            ['label' => 'Reports', 'items' => ['reports']],
            ['label' => 'Administration', 'items' => ['staff', 'support', 'settings']],
        ],

    ],
    'stadium' => [
        'code_prefix' => 'STD',
        'name' => 'Stadium / Sports Facility',
        'category' => 'sports',
        'subtitle' => 'Sports & Facilities',
        'settings_label' => 'Stadium Settings',
        'dashboard_profile_key' => 'stadium',
        'navigation_profile_key' => 'stadium',
        'labels' => [
            'workspace' => 'facility', 'information' => 'Stadium Information',
            'customer' => 'Customer',
            'customers' => 'Customers',
            'staff' => 'Staff',
            'booking' => 'Reservation',
            'bookings' => 'Reservations',
            'service' => 'Facility',
            'services' => 'Facilities',
        ],
        'modules' => [
            'dashboard' => true, 'settings' => true, 'support' => true,
            'patients' => false,
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => false,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => false,
            'prescriptions' => false,
            'pharmacy' => false,
            'facilities' => false,
            'events' => false,
        ],
        'navigation_profile' => [
            ['label' => 'Dashboard', 'items' => ['dashboard']],
            ['label' => 'Operations', 'items' => ['billing']],
            ['label' => 'Reports', 'items' => ['reports']],
            ['label' => 'Administration', 'items' => ['staff', 'support', 'settings']],
        ],

    ],
];
