<?php

return [
    'clinic' => [
        'name' => 'Healthcare / Clinic',
        'category' => 'healthcare',
        'dashboard_profile_key' => 'clinic',
        'navigation_profile_key' => 'clinic',
        'labels' => [
            'customer' => 'Patient',
            'customers' => 'Patients',
            'staff' => 'Staff',
            'booking' => 'Appointment',
            'bookings' => 'Appointments',
            'service' => 'Consultation',
            'services' => 'Consultations',
        ],
        'modules' => [
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => true,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => true,
            'prescriptions' => true,
            'pharmacy' => true,
            'facilities' => false,
            'events' => false,
        ],
    ],
    'dental' => [
        'name' => 'Dental Clinic',
        'category' => 'healthcare',
        'dashboard_profile_key' => 'clinic',
        'navigation_profile_key' => 'clinic',
        'labels' => [
            'customer' => 'Patient',
            'customers' => 'Patients',
            'staff' => 'Staff',
            'booking' => 'Appointment',
            'bookings' => 'Appointments',
            'service' => 'Dental Consultation',
            'services' => 'Dental Consultations',
        ],
        'modules' => [
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => true,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => true,
            'prescriptions' => true,
            'pharmacy' => true,
            'facilities' => false,
            'events' => false,
        ],
    ],
    'beauty-salon' => [
        'name' => 'Beauty Salon',
        'category' => 'beauty',
        'dashboard_profile_key' => 'beauty-salon',
        'navigation_profile_key' => 'beauty-salon',
        'labels' => [
            'customer' => 'Client',
            'customers' => 'Clients',
            'staff' => 'Stylist',
            'staff_plural' => 'Stylists',
            'booking' => 'Appointment',
            'bookings' => 'Appointments',
            'service' => 'Service',
            'services' => 'Services',
        ],
        'modules' => [
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => true,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => false,
            'prescriptions' => false,
            'pharmacy' => false,
            'facilities' => false,
            'events' => false,
        ],
    ],
    'stadium' => [
        'name' => 'Stadium / Sports Facility',
        'category' => 'sports',
        'dashboard_profile_key' => 'stadium',
        'navigation_profile_key' => 'stadium',
        'labels' => [
            'customer' => 'Customer',
            'customers' => 'Customers',
            'staff' => 'Staff',
            'booking' => 'Reservation',
            'bookings' => 'Reservations',
            'service' => 'Facility',
            'services' => 'Facilities',
        ],
        'modules' => [
            'customers' => true,
            'bookings' => true,
            'staff' => true,
            'services' => false,
            'billing' => true,
            'reports' => true,
            'inventory' => false,
            'clinical' => false,
            'prescriptions' => false,
            'pharmacy' => false,
            'facilities' => false,
            'events' => false,
        ],
    ],
];
