<?php

return [
    'articles' => [
        [
            'slug' => 'dashboard-overview',
            'title' => 'Dashboard Overview',
            'category' => 'GETTING STARTED',
            'summary' => 'Learn what the clinic dashboard shows and how to navigate the main modules.',
            'keywords' => ['dashboard', 'overview', 'clinic', 'workspace'],
            'updated_at' => '2026-09-12',
            'content' => [
                'The dashboard gives you an instant view of today\'s clinic activity, patients, appointments, and staff availability.',
                'Use the left navigation to move between Patients, Appointments, Doctors, Prescriptions, Billing, Reports, Staff, Settings, and Help & Support.',
                'The clinic and branch selectors in the top bar let you switch tenant contexts and branch-specific workflows while keeping the same workspace layout.',
                'If you see a module locked or unavailable, check your role permissions or subscription plan before contacting support.',
            ],
            'related' => ['switching-clinics', 'switching-branches', 'understanding-roles'],
        ],
        [
            'slug' => 'switching-clinics',
            'title' => 'Switching Clinics',
            'category' => 'GETTING STARTED',
            'summary' => 'Move between different clinics you have access to without leaving the workspace.',
            'keywords' => ['clinics', 'tenant', 'switch', 'workspace'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the clinic switcher in the top bar to see your available clinics.',
                'Select a different clinic and confirm the branch that should remain active for your current session.',
                'Clinic access is controlled by your permissions and the clinic\'s active subscription.',
            ],
            'related' => ['dashboard-overview', 'switching-branches'],
        ],
        [
            'slug' => 'switching-branches',
            'title' => 'Switching Branches',
            'category' => 'GETTING STARTED',
            'summary' => 'Use the branch selector to change branch context when your clinic has multiple locations.',
            'keywords' => ['branch', 'switch', 'location'],
            'updated_at' => '2026-09-12',
            'content' => [
                'The branch selector is available from the top bar and shows the currently active branch.',
                'Choose a branch to update patient, appointment, and staff views with that branch\'s data.',
                'If a branch is unavailable, confirm that your account has access and the clinic subscription is active.',
            ],
            'related' => ['dashboard-overview', 'switching-clinics'],
        ],
        [
            'slug' => 'understanding-roles',
            'title' => 'Understanding Roles',
            'category' => 'GETTING STARTED',
            'summary' => 'Understand how role-based access determines which modules are available to each user.',
            'keywords' => ['roles', 'permissions', 'access'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Each clinic member is assigned a role such as owner, admin, staff, receptionist, doctor, nurse, pharmacist, cashier, or management.',
                'Roles define the permissions granted for modules like Patients, Appointments, Doctors, Prescriptions, Billing, and Settings.',
                'If a feature is grayed out or blocked, your clinic administrator can update your role or branches.',
            ],
            'related' => ['dashboard-overview', 'add-staff'],
        ],
        [
            'slug' => 'register-a-patient',
            'title' => 'Register a Patient',
            'category' => 'PATIENT CARE',
            'summary' => 'Create a patient record and capture the primary details required for care.',
            'keywords' => ['patient', 'register', 'patient record'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the Patients module and select Add Patient or Create Patient.',
                'Enter the patient\'s personal details, contact information, and key demographic information.',
                'Review the record and save it before scheduling appointments or creating prescriptions.',
            ],
            'related' => ['edit-patient-details', 'patient-medical-history'],
        ],
        [
            'slug' => 'edit-patient-details',
            'title' => 'Edit Patient Details',
            'category' => 'PATIENT CARE',
            'summary' => 'Update existing patient information without creating duplicate records.',
            'keywords' => ['patient', 'edit', 'update'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the patient profile and choose Edit Patient.',
                'Update any missing or changed details, then save the changes.',
                'Use the patient activity view to review recent changes.',
            ],
            'related' => ['register-a-patient', 'patient-medical-history'],
        ],
        [
            'slug' => 'patient-medical-history',
            'title' => 'Patient Medical History',
            'category' => 'PATIENT CARE',
            'summary' => 'Record allergies, conditions, and medical notes that support clinical care.',
            'keywords' => ['medical history', 'allergies', 'conditions'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the patient profile and navigate to the Medical History section.',
                'Maintain allergies, diagnoses, and other clinical notes as part of the patient\'s care plan.',
                'This information is useful for future appointments, prescriptions, and consultation workflows.',
            ],
            'related' => ['register-a-patient', 'start-consultation'],
        ],
        [
            'slug' => 'create-appointment',
            'title' => 'Create Appointment',
            'category' => 'APPOINTMENTS',
            'summary' => 'Schedule a patient visit for the right doctor, time, and branch.',
            'keywords' => ['appointment', 'schedule', 'book'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Go to Appointments and select a booking flow for the patient.',
                'Choose the date, time, doctor, branch, and appointment type.',
                'Save the appointment to make it visible in the booking calendar and daily schedule.',
            ],
            'related' => ['reschedule-appointment', 'cancel-appointment', 'check-in-patient'],
        ],
        [
            'slug' => 'reschedule-appointment',
            'title' => 'Reschedule Appointment',
            'category' => 'APPOINTMENTS',
            'summary' => 'Move an existing appointment to a new date or time without losing the booking details.',
            'keywords' => ['reschedule', 'update', 'appointment'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the appointment details page and select the reschedule action.',
                'Update the appointment date, time, or doctor as needed.',
                'Re-save the appointment so the calendar and reminders remain accurate.',
            ],
            'related' => ['create-appointment', 'cancel-appointment'],
        ],
        [
            'slug' => 'cancel-appointment',
            'title' => 'Cancel Appointment',
            'category' => 'APPOINTMENTS',
            'summary' => 'Cancel or mark an appointment as no-show when the visit cannot proceed.',
            'keywords' => ['cancel', 'appointment', 'no-show'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Use the appointment status controls to cancel a booking or mark it as completed.',
                'Record the reason when appropriate so the visit can be tracked accurately.',
                'Cancelled appointments should be reviewed during later clinic reporting.',
            ],
            'related' => ['create-appointment', 'check-in-patient'],
        ],
        [
            'slug' => 'check-in-patient',
            'title' => 'Check In Patient',
            'category' => 'APPOINTMENTS',
            'summary' => 'Update arrival and check-in status for a scheduled patient visit.',
            'keywords' => ['check-in', 'arrival', 'appointment'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the patient appointment from the schedule or appointment list.',
                'Select the check-in action to mark the patient as arrived.',
                'This helps staff keep the waiting list and consultation flow organized.',
            ],
            'related' => ['create-appointment', 'start-consultation'],
        ],
        [
            'slug' => 'start-consultation',
            'title' => 'Start Consultation',
            'category' => 'CLINICAL',
            'summary' => 'Launch a consultation workflow for an arriving patient.',
            'keywords' => ['consultation', 'clinical', 'doctor'],
            'updated_at' => '2026-09-12',
            'content' => [
                'From an active appointment, begin a consultation to open the patient\'s clinical workspace.',
                'Capture vital sign data, exam notes, diagnosis, and treatment instructions.',
                'A consultation can be followed by prescription creation and future follow-up scheduling.',
            ],
            'related' => ['record-vitals', 'create-prescription'],
        ],
        [
            'slug' => 'record-vitals',
            'title' => 'Record Vitals',
            'category' => 'CLINICAL',
            'summary' => 'Document observations during a patient consultation.',
            'keywords' => ['vitals', 'consultation', 'clinical'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Within the consultation workspace, record the patient\'s temperature, blood pressure, pulse, and other observations.',
                'Store findings in the patient record so future visits can reference the same clinical context.',
            ],
            'related' => ['start-consultation', 'add-diagnosis'],
        ],
        [
            'slug' => 'add-diagnosis',
            'title' => 'Add Diagnosis',
            'category' => 'CLINICAL',
            'summary' => 'Capture diagnosis details during patient review.',
            'keywords' => ['diagnosis', 'clinical', 'consultation'],
            'updated_at' => '2026-09-12',
            'content' => [
                'In the consultation view, add a diagnosis or treatment plan for the patient.',
                'Use the clear notes and summaries to support the next steps in care.',
            ],
            'related' => ['start-consultation', 'create-prescription'],
        ],
        [
            'slug' => 'create-prescription',
            'title' => 'Create Prescription',
            'category' => 'CLINICAL',
            'summary' => 'Generate a prescription from an active consultation record.',
            'keywords' => ['prescription', 'medication', 'drug'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Create a prescription from the patient record or consultation view.',
                'Add medications, dosage details, and follow-up instructions before saving the prescription.',
                'Printed or shared prescriptions can be sent to Pharmacy or patient-facing workflows as needed.',
            ],
            'related' => ['start-consultation', 'print-receipt'],
        ],
        [
            'slug' => 'create-invoice',
            'title' => 'Create Invoice',
            'category' => 'BILLING',
            'summary' => 'Generate an invoice for clinic services and patient care.',
            'keywords' => ['invoice', 'billing', 'payment'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the Billing module and choose billing actions to create an invoice for a patient.',
                'Add line items, review services, and save the invoice for printing or payment processing.',
            ],
            'related' => ['record-payment', 'print-receipt'],
        ],
        [
            'slug' => 'record-payment',
            'title' => 'Record Payment',
            'category' => 'BILLING',
            'summary' => 'Record payments received and keep patient billing up to date.',
            'keywords' => ['payment', 'billing', 'invoice'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the invoice and use the payment option to record the patient\'s payment amount.',
                'A saved payment updates the outstanding balance and supports accurate billing reports.',
            ],
            'related' => ['create-invoice', 'print-receipt'],
        ],
        [
            'slug' => 'print-receipt',
            'title' => 'Print Receipt',
            'category' => 'BILLING',
            'summary' => 'Print and share billing confirmations for completed transactions.',
            'keywords' => ['receipt', 'print', 'invoice'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Invoices and payments can be printed as receipts for patient-facing confirmation.',
                'Use the print or PDF actions from the billing or invoice pages to generate a clean document.',
            ],
            'related' => ['create-invoice', 'record-payment'],
        ],
        [
            'slug' => 'generate-patient-report',
            'title' => 'Generate Patient Report',
            'category' => 'REPORTS',
            'summary' => 'Prepare patient-focused reports for review and export.',
            'keywords' => ['report', 'patient', 'export'],
            'updated_at' => '2026-09-12',
            'content' => [
                'The Reports module includes patient registration, demographics, and other patient summary reports.',
                'Select a report type and choose whether you want to view, print, or export the output.',
            ],
            'related' => ['generate-appointment-report', 'print-pdf'],
        ],
        [
            'slug' => 'generate-appointment-report',
            'title' => 'Generate Appointment Report',
            'category' => 'REPORTS',
            'summary' => 'Review appointment usage and clinic performance with scheduled reports.',
            'keywords' => ['appointment', 'report', 'performance'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open the appointment reports section to view activity by status, doctor, or date range.',
                'Use your selected filters to build a report that matches the specific clinic management question.',
            ],
            'related' => ['generate-patient-report', 'print-pdf'],
        ],
        [
            'slug' => 'print-pdf',
            'title' => 'Print PDF',
            'category' => 'REPORTS',
            'summary' => 'Generate printable PDF output for clinic records and reports.',
            'keywords' => ['pdf', 'print', 'report'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Use the accessible print or PDF actions in the report views when you need a printable copy.',
                'Printed reports can be shared with clinic leaders or stored for audit purposes.',
            ],
            'related' => ['generate-patient-report', 'generate-appointment-report'],
        ],
        [
            'slug' => 'add-staff',
            'title' => 'Add Staff',
            'category' => 'ADMINISTRATION',
            'summary' => 'Create clinic staff accounts, assign roles, and control branch access.',
            'keywords' => ['staff', 'users', 'account'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Open Users / Staff to create a new staff profile for the clinic.',
                'Assign a role, select branches, and save the account so the member can access the permitted features.',
            ],
            'related' => ['understanding-roles', 'branch-access', 'clinic-settings'],
        ],
        [
            'slug' => 'branch-access',
            'title' => 'Branch Access',
            'category' => 'ADMINISTRATION',
            'summary' => 'Control which branches a member can access from their account.',
            'keywords' => ['branches', 'access', 'permissions'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Use the staff member edit form to control whether a user can access all branches or only selected locations.',
                'Restricting branch access helps keep the clinic workspace secure and aligned with role responsibilities.',
            ],
            'related' => ['add-staff', 'clinic-settings'],
        ],
        [
            'slug' => 'clinic-settings',
            'title' => 'Clinic Settings',
            'category' => 'ADMINISTRATION',
            'summary' => 'Configure clinic branding, branch settings, appointment preferences, and general account details.',
            'keywords' => ['settings', 'clinic', 'configuration'],
            'updated_at' => '2026-09-12',
            'content' => [
                'Clinic administrators can manage branding, subscription details, branches, and other support settings from the Settings area.',
                'Review the different sections carefully before changing operational settings that affect live workflows.',
            ],
            'related' => ['add-staff', 'branch-access'],
        ],
    ],
    'faqs' => [
        [
            'question' => 'How do I reset my password?',
            'answer' => 'Use the password reset flow on the login page or ask your clinic administrator to reset it from the Users / Staff module.',
        ],
        [
            'question' => 'How do I add another staff member?',
            'answer' => 'Go to Users / Staff, choose Add Staff Member, provide the person\'s details, assign a role and branches, and save the account.',
        ],
        [
            'question' => 'Why can\'t I access Pharmacy?',
            'answer' => 'Pharmacy is only available when your account holds the required permissions and the subscription has the relevant feature enabled.',
        ],
        [
            'question' => 'Why can\'t I add more users?',
            'answer' => 'The clinic plan may have reached its member limit. Review the current subscription or contact the clinic administrator.',
        ],
        [
            'question' => 'How do I switch branches?',
            'answer' => 'Use the branch selector in the top navigation bar to change the active branch context for the current session.',
        ],
        [
            'question' => 'How do I print a report?',
            'answer' => 'Open the Reports module, select the report you need, then use the built-in print or PDF action from the report page.',
        ],
        [
            'question' => 'How do I upgrade my plan?',
            'answer' => 'Review the subscription section in Settings or contact the clinic administrator and platform support for plan assistance.',
        ],
    ],
];
