<script setup>
import {computed} from 'vue';import {useClinicContextStore} from '../../stores/clinicContext';import {useAppointmentStore} from '../../stores/appointments';import {addDays,calendarRange,formatDate,minutes,clock,dayDate} from '../../utils/appointmentDates';
import {positionBookings} from '../../utils/bookingLayout';
const props=defineProps({date:String,view:String,today:String,nowTime:String,compact:Boolean});const emit=defineEmits(['open','create']);const store=useAppointmentStore(),context=useClinicContextStore();
const days=computed(()=>{const range=calendarRange(props.date,props.view);return Array.from({length:props.view==='day'?1:7},(_,i)=>addDays(range.start,i));});
const start=computed(()=>Math.floor(Math.min(480,...store.hours.schedules.map(s=>minutes(s.start_time)),...store.rows.map(a=>minutes(a.starts_at.slice(11))))/60)*60);
const end=computed(()=>Math.min(1440,Math.ceil(Math.max(1080,...store.hours.schedules.map(s=>minutes(s.end_time)),...store.rows.map(a=>minutes(a.ends_at.slice(11))))/60)*60));
const scale=computed(()=>props.compact?1:1.5);
const slots=computed(()=>Array.from({length:(end.value-start.value)/30},(_,i)=>start.value+i*30));
function working(day,time){return store.hours.schedules.some(s=>s.is_available && s.day_of_week===(dayDate(day).getUTCDay()||7) && time>=minutes(s.start_time)&&time+30<=minutes(s.end_time)&&!(s.break_start&&time<minutes(s.break_end)&&time+30>minutes(s.break_start))&&!store.hours.leaves.some(l=>l.doctor_id===s.doctor_id&&l.start_date<=day&&l.end_date>=day));}
function positioned(day){ return positionBookings(store.rows.filter(a=>a.starts_at.slice(0,10)===day)); }
const nowPosition=computed(()=>(minutes(props.nowTime||'00:00')-start.value)*scale.value);
</script>
<template><div class="appointment-timeline-scroll"><div class="appointment-timeline" :style="{'--days':days.length,'--timeline-height':`${(end-start)*scale}px`}"><div class="appointment-time-heading">{{context.data.clinic.timezone.split('/').pop()}}</div><div v-for="day in days" :key="day" class="appointment-day-heading" :class="{'is-today':day===today}"><strong>{{formatDate(day,{weekday:'short'})}}</strong><span>{{formatDate(day,{month:'short',day:'numeric'})}}</span></div><div class="appointment-time-axis"><span v-for="time in slots" :key="time" :style="{top:`${(time-start)*scale}px`}">{{clock(time)}}</span></div><div v-for="day in days" :key="`${day}-body`" class="appointment-day-column" :class="{'is-today':day===today}"><button v-for="time in slots" :key="time" class="appointment-time-slot" :class="{'is-working':working(day,time)}" :style="{top:`${(time-start)*scale}px`,height:`${30*scale}px`}" :aria-label="`Book ${day} at ${clock(time)}`" :disabled="!context.can('appointments.create')||!working(day,time)" @click="emit('create',{date:day,start_time:clock(time)})"></button><button v-for="a in positioned(day)" :key="a.id" class="appointment-calendar-card" :class="`appointment-color-${store.options?.statuses[a.status]?.[1]||'gray'}`" :style="{top:`${(a.start-start)*scale}px`,height:`${Math.max((a.end-a.start)*scale-3,19)}px`,left:`calc(${100*a.lane/a.lanes}% + 2px)`,width:`calc(${100/a.lanes}% - 4px)`}" :title="`${a.patient.full_name} · ${a.doctor.full_name} · ${a.starts_at.slice(11,16)}–${a.ends_at.slice(11,16)} · ${store.options?.statuses[a.status]?.[0]}`" @click="emit('open',a)"><small>{{a.starts_at.slice(11,16)}}–{{a.ends_at.slice(11,16)}}</small><strong>{{a.patient.full_name}}</strong><span>{{a.type || a.doctor.full_name}}</span></button><div v-if="day===today&&nowPosition>=0&&nowPosition<(end-start)*scale" class="appointment-now" :style="{top:`${nowPosition}px`}"><span>{{nowTime}}</span></div></div></div></div></template>
