<script setup>
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useClinicContextStore } from '../../../stores/clinicContext';
import { useSalonBookingStore } from '../../../stores/salonBookings';
import { salonBookingApi as api } from '../../../services/salonBookings';
import { calendarRange, addDays, moveMonth, formatDate } from '../../../utils/appointmentDates';
import BookingTimeline from '../../../components/appointments/BookingTimeline.vue';
import AppointmentMonthView from '../../../components/appointments/AppointmentMonthView.vue';
import FormErrors from '../../../components/ui/FormErrors.vue';
const route=useRoute(),router=useRouter(),context=useClinicContextStore(),store=useSalonBookingStore();
const search=ref(route.query.search||''), selected=ref(null), detailError=ref(null), busy=ref(false), reason=ref(''), showToday=ref(false), activity=ref([]);
let detailVersion=0, timer;
const view=computed(()=>['day','week','month','schedule','stylist'].includes(route.query.view)?route.query.view:window.innerWidth<700?'day':'week');
const date=computed(()=>/^\d{4}-\d{2}-\d{2}$/.test(route.query.date||'')?route.query.date:context.data.today);
const range=computed(()=>calendarRange(date.value,view.value==='stylist'?'day':view.value));
const filters=computed(()=>({...range.value,branch_id:route.query.branch_id||context.data.branch.id,stylist_id:route.query.stylist_id||'',service_id:route.query.service_id||'',status:route.query.status||'',search:route.query.search||''}));
const columns=computed(()=>view.value==='stylist'?(store.options?.stylists||[]).filter(s=>!filters.value.stylist_id||s.id===Number(filters.value.stylist_id)).map(s=>({key:s.id,label:s.name,date:date.value,stylist_id:s.id})):Array.from({length:view.value==='day'?1:7},(_,i)=>{const d=addDays(range.value.start,i);return {key:d,date:d,label:formatDate(d,{weekday:'short'})};}));
const actions=computed(()=>Object.entries(store.options?.actions||{}).filter(([,a])=>a.from.includes(selected.value?.status)&&context.can(a.permission)));
const actionLabels={'confirm':'Confirm','check-in':'Check In','start-service':'Start Service','complete':'Complete','cancel':'Cancel Appointment','no-show':'No Show'};
const todayTotal=computed(()=>Object.values(store.summary||{}).reduce((total,count)=>total+Number(count),0));
const money=a=>`${a.currency} ${Number(a.total).toFixed(2)}`;
function change(values){router.push({path:'/app/appointments',query:{...route.query,...values}});}
function move(delta){change({date:view.value==='month'?moveMonth(date.value,delta):addDays(date.value,delta*(view.value==='day'||view.value==='stylist'?1:7))});}
function create(values={}){router.push({path:'/app/appointments/create',query:{date:date.value,branch_id:filters.value.branch_id,...values}});}
function open(a){router.push({path:'/app/appointments/'+a.id,query:route.query});}
async function detail(){const token=++detailVersion;selected.value=null;activity.value=[];detailError.value=null;reason.value='';if(!route.params.id)return;try{const [r,events]=await Promise.all([api.get('appointments/'+route.params.id),api.get('appointments/'+route.params.id+'/activity')]);if(token===detailVersion){selected.value=r.data.data;activity.value=events.data.data;}}catch(e){if(token===detailVersion)detailError.value=e;}}
async function act(action){busy.value=true;detailError.value=null;try{selected.value=(await api.post('appointments/'+selected.value.id+'/'+action,{reason:reason.value})).data.data;await store.load(filters.value);await detail();}catch(e){detailError.value=e;}finally{busy.value=false;}}
async function invoice(){busy.value=true;try{const r=await api.post('appointments/'+selected.value.id+'/invoice');await router.push('/app/billing/invoices/'+r.data.data.id);}catch(e){detailError.value=e;}finally{busy.value=false;}}
watch(filters,()=>store.load(filters.value),{immediate:true});watch(()=>route.params.id,detail,{immediate:true});
watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>change({search:search.value}),300);});
onBeforeUnmount(()=>{store.clear();++detailVersion;clearTimeout(timer);});
</script>
<template><div><header class="patient-page-header"><div><h1>{{ context.label('bookings','Appointments') }}</h1><p>Client bookings, services and stylist availability.</p></div><div class="flex gap-2 flex-wrap"><RouterLink class="btn-secondary" to="/app/appointments/hours">Business Hours</RouterLink><button v-if="context.can('appointments.create')&&store.options?.settings.allow_walk_in" class="btn-secondary" @click="create({walk_in:1})">+ Walk-In Appointment</button><button v-if="context.can('appointments.create')" class="btn" @click="create()">+ New Appointment</button></div></header>
<FormErrors :error="store.error"/><div class="clinic-panel p-4 mb-4"><div class="flex flex-wrap gap-3 items-end"><label class="field">Location<select :value="filters.branch_id" aria-label="Location" @change="change({branch_id:$event.target.value,stylist_id:'',service_id:''})"><option v-for="b in context.data.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select></label><label class="field">Search<input v-model="search" placeholder="Client, phone, stylist, service or booking"></label><label class="field">Stylist<select :value="filters.stylist_id" aria-label="Stylist filter" @change="change({stylist_id:$event.target.value})"><option value="">All Stylists</option><option v-for="s in store.options?.stylists" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label class="field">Service<select :value="filters.service_id" aria-label="Service filter" @change="change({service_id:$event.target.value})"><option value="">All Services</option><option v-for="s in store.options?.services" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label class="field">Status<select :value="filters.status" aria-label="Status filter" @change="change({status:$event.target.value})"><option value="">All</option><option v-for="(s,key) in store.options?.statuses" :key="key" :value="key">{{ s[0] }}</option></select></label></div></div>
<div class="flex items-center flex-wrap gap-2 mb-4"><button class="btn-secondary" aria-label="Previous" @click="move(-1)">←</button><button class="btn-secondary" @click="change({date:context.data.today})">Today</button><button class="btn-secondary" aria-label="Next" @click="move(1)">→</button><label class="field"><span class="sr-only">Calendar date</span><input :value="date" type="date" aria-label="Calendar date" @change="change({date:$event.target.value})"></label><button v-for="[key,label] in [['day','Day'],['week','Week'],['month','Month'],['schedule','Schedule'],['stylist','Stylist View']]" :key="key" :class="view===key?'btn':'btn-secondary'" :aria-pressed="view===key" @click="change({view:key})">{{ label }}</button></div>
<p v-if="store.busy" role="status" class="mb-3">Loading appointments…</p><div class="salon-calendar-layout"><section class="clinic-panel overflow-hidden min-w-0"><AppointmentMonthView v-if="view==='month'" :date="date" :today="context.data.today" :counts="store.counts" @day="change({date:$event,view:'day'})"/>
<div v-else-if="view==='schedule'" class="overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Time</th><th>Client</th><th>Service</th><th>Stylist</th><th>Location</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="a in store.rows" :key="a.id"><td>{{ a.starts_at.slice(0,16) }}</td><td>{{ a.client.full_name }}</td><td>{{ a.items.map(i=>i.name).join(', ') }}</td><td>{{ a.stylist.name }}</td><td>{{ a.location }}</td><td>{{ money(a) }}</td><td>{{ store.options?.statuses[a.status]?.[0] }}</td><td><button class="text-emerald-700" @click="open(a)">View</button></td></tr><tr v-if="!store.rows.length"><td colspan="8" class="p-6">No appointments match these filters.</td></tr></tbody></table></div>
<BookingTimeline v-else-if="columns.length" :columns="columns" :rows="store.rows" :statuses="store.options?.statuses||{}" :can-create="context.can('appointments.create')" @open="open" @create="create"/><p v-else class="p-6">No stylists match this location.</p></section>
<aside class="clinic-panel salon-today"><div class="clinic-card-heading"><h2>Today</h2><time>{{ formatDate(context.data.today,{weekday:'short',month:'short',day:'numeric'}) }}</time></div><div class="salon-today-stats"><div><strong>{{ todayTotal }}</strong><small>Appointments</small></div><div><strong>{{ store.summary.checked_in||0 }}</strong><small>Checked In</small></div><div><strong>{{ store.summary.in_service||0 }}</strong><small>In Service</small></div><div><strong>{{ store.summary.completed||0 }}</strong><small>Completed</small></div></div><h3 class="appointment-panel-tab">Appointments</h3><div class="salon-status-filters"><button :class="{selected:!filters.status}" @click="change({status:''})">All<strong>{{ todayTotal }}</strong></button><button v-for="([label,color],key) in store.options?.statuses" :key="key" :class="[`appointment-color-${color}`,{selected:filters.status===key}]" @click="change({status:filters.status===key?'':key})">{{ label }}<strong>{{ store.summary[key]||0 }}</strong></button></div><details class="salon-today-filters"><summary>Today's appointments</summary><div class="salon-today-list"><button v-for="a in store.today" :key="a.id" class="salon-today-row" @click="open(a)"><time>{{ a.starts_at.slice(11,16) }}<small>{{ a.ends_at.slice(11,16) }}</small></time><span><strong>{{ a.client.full_name }}</strong><small>{{ a.items.map(i=>i.name).join(', ') }}</small><small>{{ a.stylist.name }} · {{ store.options?.statuses[a.status]?.[0] }}</small></span></button><p v-if="!store.today.length" class="salon-today-empty">No appointments today for these filters.</p></div></details></aside></div>
<div v-if="route.params.id" class="fixed inset-0 z-50 bg-slate-900/30 flex justify-end" @click.self="change({})"><section class="bg-white w-full max-w-lg overflow-y-auto p-6" role="dialog" aria-modal="true" aria-labelledby="booking-detail-title"><button class="btn-secondary float-right" @click="change({})">Close</button><FormErrors :error="detailError"/><template v-if="selected"><h2 id="booking-detail-title" class="text-xl font-semibold">{{ selected.appointment_number }}</h2><h3 class="font-semibold mt-5">{{ selected.client.full_name }}</h3><p>{{ selected.client.phone }}</p><p>{{ selected.starts_at.slice(0,16) }}–{{ selected.ends_at.slice(11,16) }}</p><p>{{ selected.stylist.name }} · {{ selected.location }}</p><p class="my-3 font-semibold">{{ store.options?.statuses[selected.status]?.[0] }}</p><ul class="space-y-2"><li v-for="item in selected.items" :key="item.service_id">{{ item.name }} · {{ item.duration_minutes }} min · {{ selected.currency }} {{ Number(item.unit_price).toFixed(2) }}</li></ul><p class="font-semibold my-3">Total: {{ money(selected) }}</p><p v-if="Number(selected.deposit_required)">Deposit requirement: {{ selected.currency }} {{ Number(selected.deposit_required).toFixed(2) }}</p><p class="whitespace-pre-wrap my-3">{{ selected.notes }}</p>
<div class="flex flex-wrap gap-2 my-4"><RouterLink v-if="!['completed','cancelled','no_show','in_service'].includes(selected.status)&&context.can('appointments.update')" class="btn-secondary" :to="`/app/appointments/${selected.id}/edit`">Edit Appointment</RouterLink><RouterLink v-if="!['completed','cancelled','no_show','in_service'].includes(selected.status)&&context.can('appointments.reschedule')" class="btn-secondary" :to="`/app/appointments/${selected.id}/reschedule`">Reschedule Appointment</RouterLink></div><label v-if="actions.some(([key])=>key==='cancel')" class="field mb-3">Cancellation Reason<textarea v-model="reason" maxlength="1000"></textarea></label><div class="flex flex-wrap gap-2"><button v-for="[action] in actions" :key="action" class="btn-secondary" :disabled="busy||(action==='cancel'&&!reason.trim())" @click="act(action)">{{ actionLabels[action] }}</button><RouterLink v-if="selected.invoice_id&&context.allowed('billing')" class="btn" :to="'/app/billing/invoices/'+selected.invoice_id">View Invoice</RouterLink><button v-else-if="selected.status==='completed'&&context.allowed('billing')&&context.can('billing.create')" class="btn" :disabled="busy" @click="invoice">Create Invoice</button></div><h3 class="font-semibold mt-6">Activity</h3><ul><li v-for="(event,i) in activity" :key="i" class="text-sm my-2">{{ event.action.replaceAll('salon.appointment.','').replaceAll('-',' ') }} · {{ new Date(event.created_at).toLocaleString() }}</li></ul></template><p v-else-if="!detailError">Loading appointment…</p></section></div></div></template>
<style scoped>.salon-calendar-layout{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:1rem}th,td{text-align:left;padding:.8rem;border-bottom:1px solid #e2e8f0}.salon-today{padding:16px}.salon-today .clinic-card-heading{margin-bottom:16px}.salon-today .clinic-card-heading time{font-size:11px;color:#6a8199}.salon-today-stats{display:grid;grid-template-columns:1fr 1fr;gap:9px}.salon-today-stats>div{border:1px solid #e5edf4;border-radius:8px;padding:12px;background:linear-gradient(120deg,#f4f9ff,white)}.salon-today-stats strong{font-size:23px;display:block;color:#102844}.salon-today-stats small{font-size:10px;color:#688397}.salon-status-filters{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:12px 0}.salon-status-filters button{font-size:9px;border-radius:7px;padding:9px 3px;border:1px solid transparent}.salon-status-filters strong{display:block;font-size:15px;margin-top:3px}.salon-status-filters .selected{background:#00635c;color:white}.salon-today-filters{border-top:1px solid #e8eef4;padding-top:14px}.salon-today-filters summary{cursor:pointer;font-size:12px;font-weight:700;color:#102844}.salon-today-list{margin-top:8px}.salon-today-row{display:flex;align-items:flex-start;gap:9px;width:100%;text-align:left;padding:12px 0;border-bottom:1px solid #edf2f6;font-size:11px}.salon-today-row time{color:#486785;line-height:1.35}.salon-today-row time small{display:block;color:#8aa0b1;font-size:9px}.salon-today-row span{min-width:0;flex:1}.salon-today-row strong,.salon-today-row small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.salon-today-row small{color:#698297;margin-top:4px;font-size:10px}.salon-today-empty{padding:18px 0;text-align:center;color:#7890a3;font-size:11px}@media(max-width:1100px){.salon-calendar-layout{grid-template-columns:minmax(0,1fr)}.salon-today-body{display:none}.salon-today-body.is-open{display:block}}@media(max-width:600px){.salon-today-stats{grid-template-columns:1fr 1fr}}</style>
