<script setup>
import { onMounted, ref, watch } from 'vue';
import api from '../../../services/api';
import AppIcon from '../../../components/ui/AppIcon.vue';
import ClinicStatusBadge from '../../../components/admin/ClinicStatusBadge.vue';
import FormErrors from '../../../components/ui/FormErrors.vue';

const subscriptions=ref([]),plans=ref([]),stats=ref({total:0,active:0,trial:0,cancelled:0});
const loading=ref(true),error=ref(null),search=ref(''),status=ref(''),plan=ref(''),page=ref(1),lastPage=ref(1);
let timer;
async function load(){loading.value=true;error.value=null;try{const [response,planResponse]=await Promise.all([api.get('/v1/platform/subscriptions',{params:{search:search.value,status:status.value,plan_id:plan.value,page:page.value}}),api.get('/v1/platform/plans')]);subscriptions.value=response.data.data;stats.value=response.data.stats;lastPage.value=response.data.meta.last_page;plans.value=planResponse.data.data}catch(e){error.value=e}finally{loading.value=false}}
watch([search,status,plan],()=>{page.value=1;clearTimeout(timer);timer=setTimeout(load,300)});onMounted(load);
const date=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(value)):'Not recorded';
const money=item=>new Intl.NumberFormat(undefined,{style:'currency',currency:item.currency||'USD'}).format(Number(item.price||0));
</script>

<template><div><header class="page-header"><div><p class="eyebrow">Platform administration</p><h1>Subscriptions</h1><p>Monitor clinic plans, trials and subscription status across the platform.</p></div></header><FormErrors :error="error"/>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="stat-card stat-mint"><span class="stat-icon"><AppIcon name="subscriptions" :size="28"/></span><div><p>Total Subscriptions</p><strong>{{stats.total}}</strong></div></article><article class="stat-card stat-blue"><span class="stat-icon text-blue-600"><AppIcon name="check" :size="28"/></span><div><p>Active</p><strong>{{stats.active}}</strong></div></article><article class="stat-card stat-violet"><span class="stat-icon text-violet-600"><AppIcon name="trial" :size="28"/></span><div><p>On Trial</p><strong>{{stats.trial}}</strong></div></article><article class="stat-card stat-rose"><span class="stat-icon text-rose-600"><AppIcon name="pause" :size="28"/></span><div><p>Cancelled</p><strong>{{stats.cancelled}}</strong></div></article></div>
<section class="admin-card"><div class="mb-5 grid gap-3 md:grid-cols-[1fr_180px_220px]"><input v-model="search" class="filter-input" placeholder="Search clinic or plan..."><select v-model="status" class="filter-input"><option value="">All statuses</option><option value="trial">Trial</option><option value="active">Active</option><option value="cancelled">Cancelled</option></select><select v-model="plan" class="filter-input"><option value="">All plans</option><option v-for="item in plans" :key="item.id" :value="item.id">{{item.name}}</option></select></div><p v-if="loading" class="loading-state">Loading subscriptions...</p><div v-else class="table-wrap"><table><thead><tr><th>Clinic</th><th>Plan</th><th>Status</th><th>Price</th><th>Started</th><th>Trial Ends</th><th>Usage</th><th>Snapshot Limits</th><th>Actions</th></tr></thead><tbody><tr v-for="item in subscriptions" :key="item.id"><td><p class="font-semibold">{{item.tenant_name}}</p><p class="text-xs text-slate-500">{{item.tenant_code}}</p></td><td class="font-semibold">{{item.plan_name}}</td><td><ClinicStatusBadge :status="item.status"/></td><td>{{money(item)}}<span class="block text-xs capitalize text-slate-500">{{item.billing_period}}</span></td><td>{{date(item.created_at)}}</td><td>{{date(item.trial_ends_at)}}</td><td>{{item.branches_count}} branches<br>{{item.members_count}} members</td><td>{{item.branch_limit}} branches<br>{{item.member_limit}} members</td><td><RouterLink class="btn-secondary whitespace-nowrap" :to="{name:'admin.clinics.subscription',params:{id:item.tenant_id}}">Manage</RouterLink></td></tr></tbody></table><div v-if="!subscriptions.length" class="empty-state"><p class="font-semibold">No subscriptions found</p><p>Change the filters or onboard a clinic.</p></div></div><div class="mt-5 flex items-center justify-between"><button class="btn-secondary" :disabled="page<=1" @click="page--;load()">Previous</button><span class="text-sm text-slate-500">Page {{page}} of {{lastPage}}</span><button class="btn-secondary" :disabled="page>=lastPage" @click="page++;load()">Next</button></div></section></div></template>
