<script setup>
import { onMounted, ref } from 'vue';
import { salonBookingApi as api } from '../../services/salonBookings';
import FormErrors from '../ui/FormErrors.vue';
const props=defineProps({kind:String,id:Number});const result=ref(null),error=ref(null);
async function load(page=1){try{result.value=(await api.get(`booking-history/${props.kind}/${props.id}`,{page})).data;}catch(e){error.value=e;}}
onMounted(()=>load());
</script>
<template><section class="clinic-panel p-5 mt-5"><h2 class="font-semibold text-lg">Appointment History</h2><FormErrors :error="error"/><template v-if="result"><div class="flex flex-wrap gap-6 my-4"><p>Last Visit: <strong>{{ result.last_visit?.slice(0,16)||'No completed visit' }}</strong></p><p>Next Appointment: <strong>{{ result.next_appointment?.slice(0,16)||'None scheduled' }}</strong></p><p>Booking Count: {{ result.booking_count }}</p></div><div v-if="kind==='stylists'" class="my-4"><h3 class="font-semibold">Today's Appointments</h3><p v-if="!result.today.length">No appointments today.</p><RouterLink v-for="a in result.today" :key="a.id" class="block text-emerald-700 my-2" :to="'/app/appointments/'+a.id">{{ a.starts_at.slice(11,16) }} ? {{ a.client.full_name }} ? {{ a.items.map(i=>i.name).join(', ') }}</RouterLink></div><div v-if="kind!=='clients'" class="my-4"><h3 class="font-semibold">Upcoming Appointments</h3><p v-if="!result.upcoming.length">No upcoming appointments.</p><RouterLink v-for="a in result.upcoming" :key="a.id" class="block text-emerald-700 my-2" :to="'/app/appointments/'+a.id">{{ a.starts_at.slice(0,16) }} ? {{ a.client.full_name }}</RouterLink></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Date</th><th>Client</th><th>Service</th><th>Stylist</th><th>Status</th><th>Amount</th></tr></thead><tbody><tr v-for="a in result.data" :key="a.id"><td><RouterLink class="text-emerald-700" :to="{path:'/app/appointments/'+a.id,query:{date:a.starts_at.slice(0,10),branch_id:a.branch_id}}">{{ a.starts_at.slice(0,16) }}</RouterLink></td><td>{{ a.client.full_name }}</td><td>{{ a.items.map(i=>i.name).join(', ') }}</td><td>{{ a.stylist.name }}</td><td>{{ a.status.replaceAll('_',' ') }}</td><td>{{ a.currency }} {{ Number(a.total).toFixed(2) }}</td></tr><tr v-if="!result.data.length"><td colspan="6">No appointments recorded.</td></tr></tbody></table></div><div class="flex gap-3 mt-4"><button class="btn-secondary" :disabled="result.meta.current_page<=1" @click="load(result.meta.current_page-1)">Previous</button><span>{{ result.meta.current_page }} / {{ result.meta.last_page }}</span><button class="btn-secondary" :disabled="result.meta.current_page>=result.meta.last_page" @click="load(result.meta.current_page+1)">Next</button></div></template></section></template>
<style scoped>th,td{text-align:left;padding:.7rem;border-bottom:1px solid #e2e8f0}</style>
