<script setup>
import {computed,onMounted,ref,watch} from 'vue';import api from '../../../services/api';import ClinicStatusBadge from '../../../components/admin/ClinicStatusBadge.vue';import FormErrors from '../../../components/ui/FormErrors.vue';
const clinics=ref([]),plans=ref([]),platformStats=ref({}),loading=ref(true),error=ref(null),search=ref(''),status=ref(''),plan=ref(''),page=ref(1),lastPage=ref(1);let timer;
const stats=computed(()=>({total:platformStats.value.total_clinics||0,active:platformStats.value.active_clinics||0,trial:platformStats.value.trial_clinics||0,suspended:platformStats.value.suspended_clinics||0}));
async function load(){loading.value=true;error.value=null;try{const [c,p,d]=await Promise.all([api.get('/v1/platform/tenants',{params:{search:search.value,status:status.value,plan_id:plan.value,page:page.value}}),api.get('/v1/platform/plans'),api.get('/v1/platform/dashboard')]);clinics.value=c.data.data;lastPage.value=c.data.meta.last_page;plans.value=p.data.data;platformStats.value=d.data.data.stats}catch(e){error.value=e}finally{loading.value=false}}
watch([search,status,plan],()=>{page.value=1;clearTimeout(timer);timer=setTimeout(load,300)});onMounted(load);
const fmt=v=>v?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(v)):'—';
</script><template><div><header class="page-header"><div><p class="eyebrow">Platform administration / Businesses</p><h1>Businesses / Tenants</h1><p>Manage all organizations using the Afri Clinic platform.</p></div><RouterLink class="btn" :to="{name:'admin.clinics.create'}">+ Add New Business</RouterLink></header><FormErrors :error="error"/>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="stat-card stat-mint"><div><p class="text-sm">Total Businesses</p><p class="text-3xl font-bold">{{stats.total}}</p></div></article><article class="stat-card stat-blue"><div><p class="text-sm">Active Businesses</p><p class="text-3xl font-bold">{{stats.active}}</p></div></article><article class="stat-card stat-amber"><div><p class="text-sm">Trial Businesses</p><p class="text-3xl font-bold">{{stats.trial}}</p></div></article><article class="stat-card stat-rose"><div><p class="text-sm">Suspended Businesses</p><p class="text-3xl font-bold">{{stats.suspended}}</p></div></article></div>
<section class="admin-card"><div class="mb-5 grid gap-3 md:grid-cols-[1fr_180px_200px_auto]"><input v-model="search" class="filter-input" placeholder="Search businesses…"><select v-model="status" class="filter-input"><option value="">All statuses</option><option>active</option><option>suspended</option></select><select v-model="plan" class="filter-input"><option value="">All plans</option><option v-for="item in plans" :value="item.id" :key="item.id">{{item.name}}</option></select><RouterLink class="btn text-center" :to="{name:'admin.clinics.create'}">+ Add New Business</RouterLink></div>
<p v-if="loading" class="loading-state">Loading businesses…</p><div v-else class="table-wrap"><table><thead><tr><th>Business</th><th>Code</th><th>Business Type</th><th>Owner</th><th>Plan</th><th>Status</th><th>Users</th><th>Branches</th><th>Trial / Renewal</th><th>Created</th><th>Actions</th></tr></thead><tbody><tr v-for="clinic in clinics" :key="clinic.id"><td class="font-semibold">{{clinic.name}}</td><td>{{clinic.slug}}</td><td>{{clinic.business_type?.name || '—'}}</td><td><p>{{clinic.owner?.name||'—'}}</p><p class="text-xs text-slate-500">{{clinic.owner?.email}}</p></td><td>{{clinic.plan_name||'—'}}</td><td><ClinicStatusBadge :status="clinic.status==='suspended'?'suspended':clinic.subscription_status"/></td><td>{{clinic.members_count}}</td><td>{{clinic.branches_count}}</td><td>{{fmt(clinic.trial_ends_at)}}</td><td>{{fmt(clinic.created_at)}}</td><td><RouterLink class="btn-secondary whitespace-nowrap" :to="{name:'admin.clinics.show',params:{id:clinic.id}}">View / Manage</RouterLink></td></tr></tbody></table><div v-if="!clinics.length" class="empty-state"><p class="font-semibold">No businesses found</p><p>Change the filters or create a new business.</p></div></div><div class="mt-5 flex justify-between"><button class="btn-secondary" :disabled="page<=1" @click="page--;load()">Previous</button><span class="text-sm">Page {{page}} of {{lastPage}}</span><button class="btn-secondary" :disabled="page>=lastPage" @click="page++;load()">Next</button></div></section></div></template>
