<script setup>
import { reactive, ref, watch } from 'vue';
import { defaultFeatures, planFeatureGroups } from '../../../config/planFeatures';
const props=defineProps({initial:Object,submitLabel:{type:String,default:'Create Plan'},busy:Boolean});
const emit=defineEmits(['submit','cancel']);
const limitKeys=['branch_limit','member_limit','doctor_limit','patient_limit','storage_limit_gb','appointment_limit','invoice_limit'];
const blank=()=>({name:'',slug:'',description:'',status:'active',price:0,currency:'USD',billing_period:'monthly',trial_days:14,branch_limit:1,member_limit:5,doctor_limit:null,patient_limit:null,storage_limit_gb:null,appointment_limit:null,invoice_limit:null,features:defaultFeatures()});
const form=reactive(blank()), unlimited=reactive(Object.fromEntries(limitKeys.map(k=>[k,blank()[k]===null])));
const slugEdited=ref(Boolean(props.initial));
watch(()=>props.initial,value=>{if(!value)return;Object.assign(form,blank(),value,{features:{...defaultFeatures(),...(value.features||{})}});limitKeys.forEach(k=>unlimited[k]=value[k]===null)},{immediate:true});
function send(){const payload={...form,features:{...form.features}};limitKeys.forEach(k=>payload[k]=unlimited[k]?null:Number(form[k]));emit('submit',payload)}
function slugify(){if(!props.initial&&!slugEdited.value)form.slug=form.name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
</script>
<template><form class="space-y-6" @submit.prevent="send"><section class="admin-card"><h2 class="form-section-title">Basic information</h2><div class="form-grid"><label class="field">Plan Name *<input v-model="form.name" required @input="slugify"></label><label class="field">Plan Code / Slug *<input v-model="form.slug" required pattern="[A-Za-z0-9_-]+" @input="slugEdited=true"></label><label class="field md:col-span-2">Description<textarea v-model="form.description" rows="3"></textarea></label><label class="field">Status<select v-model="form.status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label></div></section><section class="admin-card"><h2 class="form-section-title">Pricing</h2><div class="form-grid"><label class="field">Price<input v-model.number="form.price" type="number" min="0" step="0.01" required></label><label class="field">Currency<input v-model="form.currency" maxlength="3" required></label><label class="field">Billing Period<select v-model="form.billing_period"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option><option value="custom">Custom</option></select></label><label class="field">Trial Days<input v-model.number="form.trial_days" type="number" min="0" max="365" required></label></div></section><section class="admin-card"><h2 class="form-section-title">Resource limits</h2><div class="form-grid"><label v-for="key in limitKeys" :key="key" class="field"><span class="capitalize">{{key.replaceAll('_',' ').replace('gb','GB')}}</span><input v-model.number="form[key]" type="number" min="1" :disabled="unlimited[key]" :required="!unlimited[key]"><span class="hint"><input v-model="unlimited[key]" type="checkbox"> Unlimited</span></label></div></section><section class="admin-card"><h2 class="form-section-title">Healthcare features</h2><div class="feature-groups"><fieldset v-for="[group,items] in planFeatureGroups" :key="group"><legend>{{group}}</legend><label v-for="[key,label] in items" :key="key" class="feature-option"><input v-model="form.features[key]" type="checkbox">{{label}}</label></fieldset></div></section><div class="sticky-actions"><button type="button" class="btn-secondary" @click="$emit('cancel')">Cancel</button><button class="btn" :disabled="busy">{{busy?'Saving...':submitLabel}}</button></div></form></template>
